"""Regenerate full owned demo artifacts and compare canonical and split CSV hashes."""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.synthetic.cli import main
from app.synthetic.files import read_dataset
from app.synthetic.simulator import SCENARIOS


def verify(output):
    before = {s: read_dataset(output/s)[1] for s in SCENARIOS}
    parameters = {(m['seed'], m['epoch'], m['history_days'], m['upcoming_days']) for m in before.values()}
    if len(parameters) != 1:
        raise ValueError('Scenario manifests must use the same generator parameters')
    seed, epoch, history, upcoming = parameters.pop()
    main(['generate', '--output', str(output), '--seed', str(seed), '--epoch', epoch,
          '--history-days', str(history), '--upcoming-days', str(upcoming),
          '--seed-databases', '--replace-demo'])
    after = {s: read_dataset(output/s)[1] for s in SCENARIOS}
    for scenario in SCENARIOS:
        if before[scenario]['files'] != after[scenario]['files']:
            raise ValueError(f'{scenario}: regenerated bytes differ')
    report = dict(reproducible=True, seed=seed, scenarios=len(SCENARIOS),
                  identical_csv_files=sum(len(m['files']) for m in after.values()))
    (output/'reproducibility.json').write_text(json.dumps(report, indent=2)+'\n', encoding='utf-8', newline='\n')
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    verify(Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parents[2]/'artifacts'/'demo')
