import {chromium,expect as baseExpect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';
import path from 'node:path';

const ui=process.env.DEMO_TEST_UI||'http://127.0.0.1:5180',api=process.env.DEMO_TEST_API||'http://127.0.0.1:8050';
const expect=baseExpect.configure({timeout:120000});
const seed=JSON.parse(await fs.readFile('demo/seed/metadata.json','utf8'));
const out=path.resolve('artifacts/hackathon-browser');await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1000}});
context.setDefaultTimeout(120000);const page=await context.newPage(),checks=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.demoEvents=[];const Native=window.EventSource;window.EventSource=class extends Native{constructor(...args){super(...args);this.addEventListener('operation',e=>window.demoEvents.push(JSON.parse(e.data)))}}});
async function capture(name){await page.screenshot({path:path.join(out,name+'.png'),fullPage:true})}
async function nav(label){await page.getByRole('button',{name:label,exact:true}).click();await expect(page.locator('h1')).toHaveText(label)}
try{
  await page.goto(ui+'/?run='+seed.normal_run_id+'#overview');
  await page.getByRole('button',{name:'Operator access',exact:true}).click();
  await page.getByLabel('Operator access key',{exact:true}).fill('quay-local-demo-only-operator-key-2026');
  await page.getByRole('button',{name:'Unlock operations',exact:true}).click();await expect(page.locator('.access-dialog')).not.toBeVisible();
  checks.push('Documented local demo credentials authenticate through a working cookie session.');
  await expect(page.getByText('No observed queue. Pressure ahead.',{exact:true})).toBeVisible();
  expect(new URL(page.url()).searchParams.get('run')).toBe(seed.normal_run_id);
  await expect(page.getByText('Last observed queue:')).toContainText('0 vessels');
  expect(await page.getByRole('button',{name:'Scenario simulator',exact:true}).count()).toBe(0);
  expect(await page.getByRole('button',{name:'Port Operations Copilot',exact:true}).count()).toBe(0);
  checks.push('Clean seeded normal opening shows actual zero last-observed queues and focused navigation.');
  const base=(await (await context.request.get(api+'/api/v1/dashboard?run_id='+seed.normal_run_id)).json());
  const now=base.forecast_rows.find(r=>r.scope_id==='P01-T02'&&r.timestamp===base.run.as_of);
  const future=base.forecast_rows.find(r=>r.scope_id==='P01-T02'&&r.timestamp>base.run.as_of&&r.queue_length>0);
  expect(now.queue_length).toBe(0);expect(future.average_wait_hours).toBeGreaterThan(8);
  expect(new Date(future.timestamp)-new Date(base.run.as_of)).toBe(13*3600000);
  await capture('01-normal');await nav('Congestion heatmap');await page.getByLabel('Heatmap row scope').selectOption('terminal');
  await page.locator('.heat-row').filter({hasText:'Terminal 2'}).locator('.heat-cell').nth(13).click();
  await expect(page.locator('#heat-detail')).toContainText('LOW CONFIDENCE');await expect(page.locator('#heat-detail')).toContainText('13.3h');await capture('02-warning');
  checks.push('Terminal 2 forecast reveals a +13h queue before current queue formation, with causes and LOW confidence.');
  const preset=(await (await context.request.get(api+'/api/v1/dashboard?run_id='+seed.storm_run_id)).json());
  expect(preset.scenario_name).toContain('Storm + Crane Breakdown');expect(preset.recommendations.length).toBe(2);
  expect(preset.recommendations.some(r=>r.options.some(o=>o.rejection_codes.includes('DIVERSION_DISTANCE_EXCEEDS_NEARBY_PORT_LIMIT')))).toBe(true);
  checks.push('Preloaded storm what-if includes genuine capacity-aware routing and distant-diversion rejection.');
  await nav('Live operations demo');await page.getByRole('button',{name:'Start live demo',exact:true}).click();
  await expect(page.locator('.live-clock')).toContainText('SSE connected');
  const sessionId=new URL(page.url()).searchParams.get('demo');expect(sessionId).toMatch(/^[a-f0-9]{32}$/);
  await page.getByRole('button',{name:'Storm + Crane Failure',exact:true}).click();
  await expect(page.locator('.live-event-status')).toContainText('storm crane failure · SUCCEEDED');
  const storm=(await page.evaluate(()=>window.demoEvents)).findLast(e=>e.kind==='storm_crane_failure'&&e.status==='SUCCEEDED');
  expect(storm.result.event_effect.warning_lead_hours).toBe(6);expect(storm.result.changed_risks.length).toBeGreaterThan(0);
  expect(storm.result.plan_change_count).toBeGreaterThan(0);expect(storm.result.operational_plan_replaced).toBe(false);
  expect(storm.result.plan_status).toBe('DRAFT');expect(storm.result.ongoing_operation_count).toBeGreaterThan(0);
  await expect(page.getByRole('button',{name:'Approve reviewed live draft'})).toBeDisabled();await capture('03-storm');
  checks.push('Persisted storm/failure recomputes risks and a changed DRAFT through SSE; ongoing work and approval gate remain.');
  await nav('Berth planning');await expect(page.locator('.live-global-notice')).toContainText('SSE connected');await expect(page.locator('.timeline-grid')).toBeVisible();
  await page.getByRole('button',{name:'Current / FCFS',exact:true}).click();await expect(page.getByRole('button',{name:'Current / FCFS',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'Optimised',exact:true}).click();await expect(page.getByRole('button',{name:'Optimised',exact:true})).toHaveAttribute('aria-pressed','true');
  await capture('04-allocation');
  const branch=api+'/api/v1/live-demo/'+sessionId;
  const before=await (await context.request.get(branch+'/plans/'+storm.result.new_plan_id)).json();
  await nav('Live operations demo');const fresh=await (await context.request.get(branch+'/dashboard?run_id='+storm.result.new_run_id)).json();
  const candidate=fresh.waiting_predictions.slice().sort((a,b)=>b.prediction-a.prediction).find(p=>new Date(fresh.inventory.calls.find(c=>c.id===p.call_id).scheduled_eta)>new Date(fresh.run.as_of));
  await page.getByLabel('Vessel for routing comparison').selectOption(candidate.call_id);
  const routingResponse=page.waitForResponse(r=>r.url().endsWith('/recommendations/what-if')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Evaluate arrival and routing options',exact:true}).click();
  const routingResult=await (await routingResponse).json();
  await expect(page.locator('.live-routing-result')).toBeVisible();await expect(page.locator('.live-routing-result')).toContainText('Operator approval');
  const after=await (await context.request.get(branch+'/plans/'+storm.result.new_plan_id)).json();expect(after).toEqual(before);
  checks.push('Live end-to-end routing/arrival what-if displays grounded reasons and never modifies its plan.');
  await nav('Supervisor shift plan');await expect(page.getByRole('tab')).toHaveCount(9);
  for(const [label,format] of [['JSON','json'],['CSV','csv'],['Printable HTML','html']]){const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:label,exact:true}).click();const file=await downloaded;expect(file.suggestedFilename()).toContain(format);await file.saveAs(path.join(out,'updated-plan.'+format))}
  await capture('05-shifts');checks.push('Generated nine 8h supervisor shifts and working JSON/CSV exports.');
  await nav('Live operations demo');await page.getByRole('button',{name:'Recover & replan',exact:true}).click();
  await expect(page.locator('.live-event-status')).toContainText('storm crane recovery · SUCCEEDED');
  const recovery=(await page.evaluate(()=>window.demoEvents)).findLast(e=>e.kind==='storm_crane_recovery'&&e.status==='SUCCEEDED');
  expect(recovery.result.metrics.deferred_vessels).toBe(0);expect(recovery.result.operational_plan_replaced).toBe(false);
  await page.getByRole('button',{name:'Review live draft',exact:true}).click();await expect(page.getByRole('button',{name:'Approve reviewed live draft',exact:true})).toBeEnabled();
  const approved=page.waitForResponse(r=>r.url().endsWith('/plans/'+recovery.result.new_plan_id+'/approve')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Approve reviewed live draft',exact:true}).click();
  expect((await approved).status()).toBe(200);
  await expect.poll(async()=>(await (await context.request.get(branch+'/plans/'+recovery.result.new_plan_id)).json()).status).toBe('APPROVED');
  expect((await (await context.request.get(api+'/api/v1/plans/'+seed.normal_plan_id)).json()).status).toBe('APPROVED');
  checks.push('Recovery draft is complete; two explicit review/approval controls approve only the private branch, preserving normal source approval.');
  await fs.writeFile(path.join(out,'live-results.json'),JSON.stringify({storm,recovery,routingResult,normalCurrent:now,normalFuture:future},null,2));
  await nav('Strategy evaluation');await page.getByLabel('Evaluation scenario').selectOption('storm_crane_breakdown');
  const publication=await (await context.request.get(api+'/api/v1/evaluation/latest')).json();
  const baseline=publication.rows.find(r=>r.scenario_id==='storm_crane_breakdown'&&r.strategy_id==='fcfs');
  await expect(page.locator('.evaluation-view')).toContainText(new Intl.NumberFormat('en-GB',{maximumFractionDigits:1}).format(baseline.average_wait_hours));await capture('06-evaluation');
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations).toEqual([]);
  checks.push('Final four-strategy comparison displays stored simulated evidence and passes WCAG AA.');
  const backup=await context.newPage();let requests=0;backup.on('request',r=>{if(/^https?:/.test(r.url()))requests++});
  await backup.goto('file:///'+path.resolve('demo/backup/index.html').replaceAll('\\','/'));
  await expect(backup.getByText('Recorded synthetic demonstration — services may be offline.',{exact:false})).toBeVisible();
  await backup.getByRole('link',{name:'Routing gates',exact:true}).click();await expect(backup.locator('#routing')).toBeInViewport();
  expect(requests).toBe(0);expect(await backup.locator('img').count()).toBe(6);
  for(const image of await backup.locator('img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate(i=>i.naturalWidth)).toBeGreaterThan(0)}
  expect(await backup.locator('img').evaluateAll(images=>images.every(i=>i.complete&&i.naturalWidth>0))).toBe(true);
  checks.push('Standalone file backup loads all six actual screenshots and routing evidence with zero HTTP requests.');
  expect(errors).toEqual([]);await fs.writeFile(path.join(out,'verification.json'),JSON.stringify({result:'PASS',checks,errors,seed,normalCurrent:now,normalFuture:future,storm,recovery,routingResult},null,2));
  console.log('PASS: '+checks.length+' exact clean-install demonstration checks.');
}finally{await browser.close()}
