import {useEffect,useMemo,useState} from 'react';
import type {Dashboard,Forecast} from '../types';
import {hours,number,utc} from '../selectors';
import {Empty,Panel,severityLabel} from './Primitives';
import {ForecastDetail} from './ForecastDetail';
export function Heatmap({data,port,loading=false}:{data:Dashboard;port:string;loading?:boolean}){
  const [scope,setScope]=useState('all'),[selected,setSelected]=useState<Forecast|null>(null),[cursor,setCursor]=useState('0-0');
  useEffect(()=>{setSelected(null);setCursor('0-0')},[data.run.id,port,scope]);
  const groups=useMemo(()=>{const map=new Map<string,Forecast[]>();data.forecast_rows.filter(r=>(port==='all'||r.port_id===port)&&(scope==='all'||r.scope===scope)).forEach(r=>map.set(`${r.port_id}/${r.scope}/${r.scope_id}`,[...(map.get(`${r.port_id}/${r.scope}/${r.scope_id}`)||[]),r]));const order=(r:Forecast)=>{const terminal=r.scope==='berth'?data.inventory.berths.find(b=>b.id===r.scope_id)?.terminal_id:r.scope_id;return r.port_id+'/'+(r.scope==='port'?'0':terminal+'/'+(r.scope==='terminal'?'0':r.scope_id))};return [...map].sort((a,b)=>order(a[1][0]).localeCompare(order(b[1][0]))).map(([key,rows])=>({key,rows:rows.sort((a,b)=>a.timestamp.localeCompare(b.timestamp)),first:rows[0]}));},[data,port,scope]);
  function name(r:Forecast){return data.inventory.routing_ports.find(p=>p.id===r.scope_id)?.name||data.inventory.terminals.find(t=>t.id===r.scope_id)?.name||r.scope_id}
  if(loading)return <div role="status" className="loading" aria-busy="true"><h2>Loading forecast evidence</h2><p>Retrieving persisted predictions, rule thresholds and source provenance.</p></div>;
  return <Panel title="72 hours. Every pressure point." eyebrow="HOURLY CONGESTION MATRIX" action={<label className="compact-label">Rows <select aria-label="Heatmap row scope" value={scope} onChange={e=>{setScope(e.target.value);setCursor('0-0')}}><option value="all">All levels</option><option value="port">Ports</option><option value="terminal">Terminals</option><option value="berth">Berths</option></select></label>}>
    <div className="heatmap-legend">{(['LOW','MEDIUM','HIGH','CRITICAL'] as const).map(l=><span key={l}><i className={`heat-cell ${l.toLowerCase()}`}/>{severityLabel(l)}</span>)}<small>Each square is one hourly severity forecast. Select a cell, then inspect the explanation below. Arrow keys navigate.</small></div>
    {groups.length?<><div className="heat-scroll"><div className="heat-grid"><div className="heat-axis"><span className="heat-name">PORT / TERMINAL / BERTH</span>{Array.from({length:72},(_,h)=><span key={h}>{h%6===0?`+${h}h`:''}</span>)}</div>{groups.map((g,row)=><div className={`heat-row scope-${g.first.scope}`} key={g.key}><span className="heat-name"><span className="scope-tag">{g.first.scope==='port'?'P':g.first.scope==='terminal'?'T':'B'}</span>{name(g.first)}</span>{g.rows.map((cell,h)=><button data-cell={`${row}-${h}`} className={`heat-cell ${cell.congestion_severity.toLowerCase()}`} key={cell.id} tabIndex={cursor===`${row}-${h}`?0:-1} aria-label={`${name(cell)}, ${utc(cell.timestamp,true)} UTC, ${cell.congestion_severity}, confidence ${cell.confidence_level}`} aria-describedby="heat-detail" onMouseEnter={()=>setSelected(cell)} onFocus={()=>{setSelected(cell);setCursor(`${row}-${h}`)}} onClick={()=>{setSelected(cell);setCursor(`${row}-${h}`)}} onKeyDown={e=>{const offsets:Record<string,[number,number]>={ArrowRight:[0,1],ArrowLeft:[0,-1],ArrowDown:[1,0],ArrowUp:[-1,0]};if(offsets[e.key]){e.preventDefault();const [dy,dx]=offsets[e.key];document.querySelector<HTMLButtonElement>(`[data-cell="${Math.max(0,Math.min(groups.length-1,row+dy))}-${Math.max(0,Math.min(71,h+dx))}"]`)?.focus();}}}>{cell.congestion_severity==='CRITICAL'?'!':''}</button>)}</div>)}</div></div>
    <div id="heat-detail" className="forecast-detail" aria-live="polite">{selected?<><p className="eyebrow">{selected.scope} · {name(selected)} · {utc(selected.timestamp,true)} UTC / +{number(hours(selected.timestamp,data.run.as_of),0)}h</p><ForecastDetail forecast={selected}/></>:<p>Select a forecast cell to inspect predicted outcomes, recorded thresholds, known inputs and confidence.</p>}</div></>:<Empty>No hourly operational forecasts exist for the selected run and scope.</Empty>}
  </Panel>
}
