import {useEffect,useRef,useState} from 'react';
import {Activity,Clock,CloudLightning,Play,ShieldCheck} from 'lucide-react';
import type {Dashboard} from '../types';
import type {DemoSession,LiveState} from '../live';
import {request,requestControl} from '../api';
import {number,money,utc,callName} from '../selectors';
import {Badge,Panel,ReasonList} from './Primitives';

const kinds=[['eta_delay','Vessel ETA delay'],['early_arrival','Unexpected early arrival'],['crane_breakdown','Crane breakdown'],['crane_recovery','Crane recovery'],['severe_wind','Severe wind'],['yard_capacity_reduction','Yard-capacity reduction'],['berth_closure','Berth closure'],['priority_arrival','Priority-vessel arrival']];
export function LiveOperations({data,port,live,onAttach,onLeave,onReview,onApprove,busy}:{data:Dashboard;port:string;live:LiveState;onAttach:(session:DemoSession)=>void;onLeave:()=>void;onReview:()=>void;onApprove:()=>void;busy:boolean}){
  const [kind,setKind]=useState('eta_delay'),[entity,setEntity]=useState(''),[hours,setHours]=useState(6),[duration,setDuration]=useState(8),[wind,setWind]=useState(18),[capacity,setCapacity]=useState(75),[advance,setAdvance]=useState(15),[auto,setAuto]=useState(false),[starting,setStarting]=useState(false),[error,setError]=useState<string|null>(null),[all,setAll]=useState(false);
  const session=live.session,event=live.events[0],result=event?.status==='SUCCEEDED'?event.result:null;
  const [routingCall,setRoutingCall]=useState(''),[routingBusy,setRoutingBusy]=useState(false),[routing,setRouting]=useState<Dashboard['recommendations'][number]|null>(null);
  useEffect(()=>{setRouting(null);setRoutingCall('')},[data.run.id]);
  const disabled=busy||starting||live.pending||!!session&&session.status!=='READY';
  const options=kind.includes('crane')?data.inventory.cranes:kind==='berth_closure'?data.inventory.berths:kind==='yard_capacity_reduction'?data.inventory.terminals:data.inventory.calls;
  const field=kind.includes('crane')?'crane_id':kind==='berth_closure'?'berth_id':kind==='yard_capacity_reduction'?'terminal_id':'call_id';
  useEffect(()=>{setEntity('')},[kind,session?.id]);
  const tick=useRef({disabled,inject:live.inject});tick.current={disabled,inject:live.inject};
  useEffect(()=>{if(!auto||!session?.id)return;const timer=setInterval(()=>{if(!tick.current.disabled)tick.current.inject({kind:'clock_tick',advance_minutes:15})},30000);return()=>clearInterval(timer)},[auto,session?.id]);
  async function start(){setStarting(true);setError(null);try{const session=await requestControl<DemoSession>('/live-demo/sessions',{source_run_id:data.run.id,port_id:port==='all'?data.inventory.routing_ports[0].id:port,seed:42,time_limit_seconds:2});onAttach(session)}catch(e){setError(e instanceof Error?e.message:'Unable to start live demo')}finally{setStarting(false)}}
  async function compareRouting(){
    const call=data.inventory.calls.find(c=>c.id===routingCall);if(!call)return;
    setRoutingBusy(true);setError(null);
    try{
      const origin=new Date(data.run.as_of),eta=new Date(call.scheduled_eta),future=Math.max(0,(eta.getTime()-origin.getTime())/3600000);
      const response=await request<{recommendations:Dashboard['recommendations']}>('/recommendations/what-if',{
        source_run_id:data.run.id,call_id:call.id,
        voyages:[{call_id:call.id,position_as_of:origin.toISOString(),remaining_distance_nm:future*18,
          customer_deadline:new Date(Math.max(eta.getTime(),origin.getTime())+108*3600000).toISOString(),
          source_label:'SYNTHETIC demo assumption: ETA-consistent 18kn voyage and 108h delivery allowance'}],
        tariffs:data.inventory.terminals.map(t=>({terminal_id:t.id,port_call_usd:1500,handling_usd_per_move:50,
          inland_usd_per_teu:10,inland_hours:12,inland_co2_tonnes_per_teu:.002,cargo_booking_confirmed:true,
          source_label:'SYNTHETIC demo assumption: equal fictional tariffs and assumed confirmed booking'}))});
      setRouting(response.recommendations[0]);
    }catch(e){setError(e instanceof Error?e.message:'Routing comparison failed')}finally{setRoutingBusy(false)}
  }
  return <div className="live-operations">
    <section className="live-intro"><ShieldCheck size={24}/><div><h2>Live operations. Controlled decisions.</h2><p>An isolated copy preserves original data and approvals. Events create simulated observations, fresh forecasts and rolling drafts. Approval remains an operator decision.</p></div><Badge level={session?'LIVE DEMO':'ISOLATED DEMO'}/></section>
    {(error||live.error)&&<div className="error-banner" role="alert">{error||live.error}</div>}
    {!session?<Panel title="Start a live operations session" eyebrow="PRIVATE DATA SNAPSHOT"><p>Use the selected port and source clock. Imported ongoing work and approved reservations are retained. The original workspace remains available when you leave.</p><button className="button primary" disabled={disabled} onClick={start}><Play size={15}/>{starting?'Preparing forecast and initial draft…':'Start live demo'}</button></Panel>:<>
      <section className="live-clock"><Clock size={22}/><div><span>SIMULATED OPERATIONAL TIME</span><strong>{utc(session.clock,true)} UTC</strong><small>{session.id} · revision {session.revision} · {live.connection}</small></div><button className="button secondary" disabled={disabled} onClick={()=>live.inject({kind:'clock_tick',advance_minutes:advance})}>Advance {advance} minutes</button><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Auto advance every 30s</label><button className="button secondary" disabled={disabled} onClick={()=>{setAuto(false);onLeave()}}>Leave live demo</button></section>
      <div className="live-layout"><Panel title="Inject an operational event" eyebrow="PERSIST → DETECT → REPLAN">
        <div className="live-controls"><label>Event type<select value={kind} onChange={e=>setKind(e.target.value)} disabled={disabled}>{kinds.map(([k,label])=><option value={k} key={k}>{label}</option>)}</select></label>
          {kind!=='severe_wind'&&<label>Affected resource or vessel<select value={entity} onChange={e=>setEntity(e.target.value)} disabled={disabled}><option value="">Choose an API resource</option>{options.map(o=><option value={o.id} key={o.id}>{o.id}{'name' in o?' · '+o.name:''}</option>)}</select></label>}
          {['eta_delay','early_arrival'].includes(kind)&&<label>Arrival difference (hours)<input type="number" min={.25} max={48} step={.25} value={hours} onChange={e=>setHours(Number(e.target.value))}/></label>}
          {kind==='severe_wind'&&<label>Wind (m/s)<input type="number" min={10} max={45} value={wind} onChange={e=>setWind(Number(e.target.value))}/></label>}
          {kind==='yard_capacity_reduction'&&<label>Retained usable yard capacity (%)<input type="number" min={20} max={99} value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label>}
          <label>Closure / advisory duration (hours)<input type="number" min={1} max={48} value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label>
          <label>Advance before event (minutes)<select value={advance} onChange={e=>setAdvance(Number(e.target.value))}>{[15,30,60,120,240].map(m=><option value={m} key={m}>{m} minutes</option>)}</select></label>
          <button className="button primary" disabled={disabled||kind!=='severe_wind'&&!entity} onClick={()=>live.inject({kind,[field]:entity||undefined,hours,duration_hours:duration,wind_mps:wind,capacity_pct:capacity,advance_minutes:advance})}><Activity size={15}/>Inject event & replan</button>
        </div><p className="panel-footnote">Arrived or started calls cannot receive ETA changes. Yard reductions cannot hide existing inventory. Unknown breakdown repair persists until an explicit recovery event.</p>
      </Panel><Panel title="Storm + Crane Failure" eyebrow="EARLY WARNING DEMONSTRATION"><div className="live-demo-story"><CloudLightning size={34}/><p>Fail two unowned cranes and publish a storm advisory six hours ahead. Watch real forecast risks and rolling schedule changes arrive through SSE.</p><button className="button primary" disabled={disabled} onClick={()=>live.inject({kind:'storm_crane_failure',duration_hours:duration,advance_minutes:advance})}>Storm + Crane Failure</button><button className="button secondary" disabled={disabled||!live.events.some(e=>e.kind==='storm_crane_failure'&&e.status==='SUCCEEDED')} onClick={()=>live.inject({kind:'storm_crane_recovery',advance_minutes:advance})}>Recover & replan</button><p>Recovery confirms repaired cranes and cancels the demo advisory. The revised plan remains a draft.</p></div></Panel></div>
      {event&&<div className="live-event-status" role="status"><Activity size={17}/><strong>{event.kind.replaceAll('_',' ')} · {event.status}</strong><span>Event {event.sequence} · {utc(event.operational_time)} UTC</span>{event.status==='FAILED'&&<button className="button secondary" disabled={disabled} onClick={()=>live.retry(event)}>Retry persisted event</button>}</div>}
      {result&&<><div className="live-metrics">{[
        ['Forecast runtime',number(result.forecast_runtime_ms/1000)+' s'],['Optimisation runtime',number(result.optimisation_runtime_ms/1000)+' s'],['Plan changes',String(result.plan_change_count)],
        ['Waiting hours avoided',number(result.metrics.waiting_hours_avoided)+' h'],['Congestion reduction',number(result.metrics.congestion_reduction_vessel_hours)+' vessel-h'],['Cost proxy improvement',money(result.metrics.cost_improvement_usd)],['Emissions proxy improvement',number(result.metrics.emissions_improvement_tonnes_co2)+' t CO₂']
      ].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
      <p className="panel-footnote">Benefits use the same post-event FCFS inputs; congestion reduction compares matched FCFS queue area with draft queue area. Negative values are retained. Deferred vessels: {result.metrics.deferred_vessels}. Solver {result.solver_status}, {number(result.solver_runtime_ms/1000)}s; {result.ongoing_operation_count} ongoing operations and {result.frozen_assignment_count} frozen approved assignments preserved.</p>
      {result.event_effect.storm_start&&<div className="context-notice"><CloudLightning size={20}/><span><strong>Published storm warning: {result.event_effect.warning_lead_hours} hours ahead</strong> · {result.event_effect.storm_start} to {result.event_effect.storm_end}. Failed cranes: {result.event_effect.crane_ids?.join(', ')}.</span></div>}
      <Panel title="Changed congestion risks" eyebrow="OVERLAPPING UTC HORIZON"><div className="table-scroll" tabIndex={0}><table><thead><tr><th>Scope</th><th>Severity</th><th>Peak queue</th><th>Peak wait</th><th>New causes</th></tr></thead><tbody>{result.changed_risks.map(r=><tr key={r.scope+':'+r.scope_id}><td>{r.scope_id}</td><td>{r.old_severity} → {r.new_severity}</td><td>{number(r.old_peak_queue)} → {number(r.new_peak_queue)}</td><td>{number(r.old_peak_wait_hours)} → {number(r.new_peak_wait_hours)}h</td><td>{r.added_cause_codes.join(', ')||'Existing causes; magnitude changed'}</td></tr>)}</tbody></table></div>{!result.changed_risks.length&&<p>No material risk changes detected in the shared horizon.</p>}</Panel>
      <Panel title="Responsible arrival and routing decision" eyebrow="CONDITIONAL WHAT-IF · NEVER DISPATCHED">
        <label>Vessel for routing comparison<select aria-label="Vessel for routing comparison" value={routingCall} disabled={disabled||routingBusy} onChange={e=>setRoutingCall(e.target.value)}><option value="">Select a vessel at risk</option>{data.waiting_predictions.slice().sort((a,b)=>b.prediction-a.prediction).map(p=><option key={p.call_id} value={p.call_id}>{callName(data,p.call_id)} · predicted wait {number(p.prediction)}h</option>)}</select></label>
        <button className="button secondary" disabled={disabled||routingBusy||!routingCall||result.schedule_status!=='succeeded'} onClick={compareRouting}>{routingBusy?'Evaluating end-to-end impacts…':'Evaluate arrival and routing options'}</button>
        <p className="panel-footnote">Declared synthetic assumptions: 18kn ETA-consistent approach, 108h delivery allowance, $1,500 port call, $50/move handling, $10/TEU and 12h inland, assumed cargo bookings. Alternate ports require receiving resources within the source run. This comparison cannot change a plan.</p>
        {routing&&<div className="live-routing-result"><Badge level={routing.recommended_action.replaceAll('_',' ')}/><p>{number(routing.expected_hours_saved)}h end-to-end gain · {money(routing.estimated_cost_change_usd)} cost change · {number(routing.estimated_emissions_change_tonnes)}t CO₂ change. {routing.confidence_level} confidence.</p><ReasonList items={routing.main_reasons}/><details><summary>Eligibility gates and rejected alternatives</summary><div className="table-scroll"><table><thead><tr><th>Action</th><th>Eligible</th><th>Reason</th></tr></thead><tbody>{routing.options.map((o,i)=><tr key={i}><td>{o.action.replaceAll('_',' ')}</td><td>{o.eligible?'Yes':'No'}</td><td>{o.rejection_codes.join(', ')||'Compatibility, receiving capacity and net-benefit gates passed'}</td></tr>)}</tbody></table></div></details><p>Source {routing.run_id} · {data.run.as_of} UTC · expires {routing.expires_at}. {routing.is_expired?'Historical source-time comparison: expired.':''} Operator approval and fresh joint capacity certification required.</p></div>}
      </Panel>
      <Panel title="Old plan versus rolling draft" eyebrow="HUMAN APPROVAL REQUIRED" action={<div className="plan-actions"><button className="button secondary" disabled={disabled||data.run.plan?.status!=='DRAFT'} onClick={onReview}>Review live draft</button><button className="button primary" disabled={disabled||data.run.plan?.status!=='REVIEWED'||result.schedule_status!=='succeeded'} onClick={onApprove}>Approve reviewed live draft</button></div>}><p>{result.old_run_id} → {result.new_run_id}. No approved plan was replaced automatically.</p><div className="table-scroll" tabIndex={0}><table><thead><tr><th>Vessel</th><th>Before</th><th>After</th><th>Material change</th></tr></thead><tbody>{(all?result.plan_changes:result.plan_changes.slice(0,12)).map(c=><tr key={c.call_id}><td>{c.call_id}</td><td>{c.before?`${c.before.berth_id} · ${utc(c.before.start)}`:'Unassigned'}</td><td>{c.after?`${c.after.berth_id} · ${utc(c.after.start)}`:'Unassigned'}</td><td>{c.changed_fields.join(', ')}<small>{c.reason.message}</small></td></tr>)}</tbody></table></div>{result.plan_changes.length>12&&<button className="button secondary" onClick={()=>setAll(!all)}>{all?'Show first 12 changes':'Show all changes'}</button>}<ReasonList items={result.unresolved_conflicts}/><details><summary>Data provenance & assumptions</summary><p>Forecast {result.forecast_run_id} · model {result.model_version} · event {event.id}</p><ReasonList items={result.assumptions}/></details></Panel>
      </>}
      <Panel title="Persisted event log" eyebrow="RECONNECTABLE SSE"><div className="table-scroll" tabIndex={0}><table><thead><tr><th>Event</th><th>Time UTC</th><th>Status</th><th>Record</th></tr></thead><tbody>{live.events.map(e=><tr key={e.id}><td>{e.kind.replaceAll('_',' ')}</td><td>{utc(e.operational_time)}</td><td>{e.status}{e.error&&<small>{e.error.code}: {e.error.message}</small>}</td><td>{e.id}</td></tr>)}</tbody></table></div>{!live.events.length&&<p>Inject an event or advance the operational clock.</p>}</Panel>
    </>}
  </div>
}
