import {lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react';
import {TrendingUp,Bot,Activity,Anchor,ArrowUpRight,Bell,ChevronDown,Compass,FlaskConical,History,LayoutDashboard,LoaderCircle,Map,Menu,RefreshCw,Ship,SquareStack,Sun,TriangleAlert,Waves,X} from 'lucide-react';
import type {Dashboard,Plan,Run} from './types';
import {request,downloadPlan,API_BASE,setDemoContext} from './api';
import {useLiveDemo} from './live';
import type {DemoSession} from './live';
import {callName,money,number,utc} from './selectors';
import {Badge,Loading,Panel,ReasonList} from './components/Primitives';
import {Overview} from './components/Overview';
import {DemoObservations} from './components/DemoObservations';
import {OperatorAccess} from './components/OperatorAccess';
const Evaluation=lazy(()=>import('./components/Evaluation').then(module=>({default:module.Evaluation})));
const HistoricalReplay=lazy(()=>import('./components/HistoricalReplay').then(module=>({default:module.HistoricalReplay})));
const Copilot=lazy(()=>import('./components/Copilot').then(module=>({default:module.Copilot})));
const LiveOperations=lazy(()=>import('./components/LiveOperations').then(module=>({default:module.LiveOperations})));
const Heatmap=lazy(()=>import('./components/Heatmap').then(module=>({default:module.Heatmap})));
const Timeline=lazy(()=>import('./components/Timeline').then(module=>({default:module.Timeline})));
const PortMap=lazy(()=>import('./components/PortMap').then(module=>({default:module.PortMap})));
const Shifts=lazy(()=>import('./components/Shifts').then(module=>({default:module.Shifts})));
const Scenario=lazy(()=>import('./components/Scenario').then(module=>({default:module.Scenario})));

const presentation=import.meta.env.VITE_DEMO_MODE==='true';
const views=[{id:'overview',label:'Executive overview',icon:LayoutDashboard,short:'Overview'},
  {id:'heatmap',label:'Congestion heatmap',icon:SquareStack,short:'Congestion'},
  {id:'timeline',label:'Berth planning',icon:Anchor,short:'Berth planning'},
  {id:'map',label:'Port network map',icon:Map,short:'Port network'},
  {id:'shifts',label:'Supervisor shift plan',icon:Sun,short:'Shift plans'},
  {id:'scenario',label:'Scenario simulator',icon:FlaskConical,short:'Scenario lab'},
  {id:'copilot',label:'BOB Operations Copilot',icon:Bot,short:'Copilot'},
  {id:'live',label:'Live operations demo',icon:Activity,short:'Live operations'},
  {id:'historical',label:'Historical replay',icon:History,short:'Historical replay'},
  {id:'evaluation',label:'Strategy evaluation',icon:TrendingUp,short:'Evaluation'}].filter(v=>!presentation||v.id!=='scenario');

function VesselDetail({data,id,onClose}:{data:Dashboard;id:string;onClose:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal()},[]);
  const call=data.inventory.calls.find(c=>c.id===id),vessel=data.inventory.vessels.find(v=>v.id===call?.vessel_id),pred=data.waiting_predictions.find(p=>p.call_id===id),assignment=data.effective_assignments.find(a=>a.call_id===id),rec=data.recommendations.find(r=>r.call_id===id);
  return <dialog ref={dialog} className="vessel-dialog" onClose={onClose} onClick={e=>{if(e.target===dialog.current)dialog.current?.close()}} aria-labelledby="vessel-title"><div className="drawer-content"><header><div><p className="eyebrow">VESSEL INTELLIGENCE · {id}</p><h2 id="vessel-title">{callName(data,id)}</h2></div><button className="icon-button" onClick={()=>dialog.current?.close()} aria-label="Close vessel details"><X/></button></header><div className="vessel-facts"><span>Length<strong>{number(vessel?.length_m)}m</strong></span><span>Draft<strong>{number(vessel?.draft_m)}m</strong></span><span>Capacity<strong>{number(vessel?.capacity_teu,0)} TEU</strong></span><span>Priority<strong>P{call?.priority}</strong></span></div><p>{call?.cargo_type} containers · {call?.terminal_id} · ETA {call?utc(call.scheduled_eta,true):'—'} UTC</p>
    <Panel title="Waiting-time prediction" eyebrow={pred?.model_version||'MODEL EVIDENCE UNAVAILABLE'}>{pred?<><strong className="drawer-prediction">{number(pred.prediction)} h</strong><p>Uncertainty band {number(pred.lower)}–{number(pred.upper)} h · LOW synthetic confidence</p><ReasonList items={pred.factors}/></>:<p>No scheduled waiting prediction for this vessel in the selected run.</p>}</Panel>
    <Panel title="Berth & crane assignment">{assignment?<><div className="assignment-facts"><strong>{assignment.berth_id}</strong><p>Start {utc(assignment.start,true)} → completion {utc(assignment.completion_time,true)} → departure {utc(assignment.end,true)} UTC</p><p>{number(assignment.planned_moves,0)} remaining planned moves · {number(assignment.waiting_minutes/60)}h schedule wait</p></div><details><summary>Timed crane segments ({assignment.execution_profile.segments.length})</summary><div className="table-scroll"><table><thead><tr><th>Slots from origin</th><th>Cranes</th><th>Moves</th></tr></thead><tbody>{assignment.execution_profile.segments.map((s,i)=><tr key={i}><td>+{s.start_slot/4}–{s.end_slot/4}h</td><td>{s.crane_ids.join(', ')}</td><td>{number(s.moves)}</td></tr>)}</tbody></table></div></details></>:<p>No certified assignment. Check unserved conflicts and supervisor actions.</p>}</Panel>
    <Panel title="Responsible routing comparison">{rec?<><Badge level={rec.recommended_action.replaceAll('_',' ')}/><div className="context-notice">{rec.is_expired?'Expired historical what-if.':'Operator approval required.'} Receiving capacity is unreserved; refresh and jointly replan before dispatch.</div><table><thead><tr><th>Outcome</th><th>Current plan</th><th>Recommendation</th></tr></thead><tbody><tr><td>Waiting time</td><td>{number(rec.current_plan_outcome?.planned_wait_hours)}h</td><td>{number(rec.recommended_plan_outcome?.planned_wait_hours)}h</td></tr><tr><td>End-to-end cost</td><td>{money(rec.current_plan_outcome?.total_cost_usd)}</td><td>{money(rec.recommended_plan_outcome?.total_cost_usd)}</td></tr></tbody></table><p>{number(rec.expected_hours_saved)}h delivery gain · {money(rec.estimated_cost_change_usd)} cost change · {number(rec.estimated_emissions_change_tonnes)}t CO₂ change</p><ReasonList items={rec.main_reasons}/><details><summary>Risks, assumptions & expiry</summary><ReasonList items={[...rec.risks_and_assumptions,`Expires ${rec.expires_at}`]}/></details><details><summary>All evaluated alternatives ({rec.options.length})</summary><div className="table-scroll"><table><thead><tr><th>Option</th><th>Eligible</th><th>Rejection evidence</th></tr></thead><tbody>{rec.options.map((o,i)=><tr key={i}><td>{o.action.replaceAll('_',' ')}</td><td>{o.eligible?'Yes':'No'}</td><td>{o.rejection_codes.join(', ')||'Benefit and compatibility gates evaluated'}</td></tr>)}</tbody></table></div></details></>:<p>No audited routing comparison exists for this vessel. Operational changes require explicit voyage/customer inputs and a responsible what-if run.</p>}</Panel>
  </div></dialog>
}

export function App(){
  const [demoId,setDemoId]=useState<string|null>(()=>new URLSearchParams(window.location.search).get('demo'));
  setDemoContext(demoId);
  const [data,setData]=useState<Dashboard|null>(null),[view,setView]=useState(()=>views.find(v=>v.id===window.location.hash.slice(1))?.id||'overview'),[port,setPort]=useState('all'),[loading,setLoading]=useState(true),[action,setAction]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[selected,setSelected]=useState<string|null>(null),[mobile,setMobile]=useState(false),[actor,setActor]=useState('Demo supervisor');
  const [loadFailed,setLoadFailed]=useState(false);
  const abort=useRef<AbortController|null>(null);const heading=useRef<HTMLHeadingElement>(null);
  const load=useCallback(async(id?:string)=>{abort.current?.abort();const controller=new AbortController();abort.current=controller;setLoading(true);setLoadFailed(false);setError(null);try{const result=await request<Dashboard>(`/dashboard${id?'?run_id='+encodeURIComponent(id):''}`,undefined,controller.signal);if(controller.signal.aborted)return;setData(result);setPort(old=>old==='all'||result.inventory.routing_ports.some(p=>p.id===old)?old:'all');const url=new URL(window.location.href);url.searchParams.set('run',result.run.id);history.replaceState(null,'',url);}catch(e){if(!controller.signal.aborted){setLoadFailed(true);setError(e instanceof Error?e.message:'Unable to load dashboard')}}finally{if(!controller.signal.aborted)setLoading(false)}},[]);
  const live=useLiveDemo(demoId,run=>load(run));
  function attach(session:DemoSession){setDemoContext(session.id);setDemoId(session.id);const url=new URL(window.location.href);url.searchParams.set('demo',session.id);history.replaceState(null,'',url);load(session.latest_run_id)}
  function leave(){setDemoContext(null);setDemoId(null);const url=new URL(window.location.href);url.searchParams.delete('demo');url.searchParams.delete('run');history.replaceState(null,'',url);load()}
  useEffect(()=>{load(new URLSearchParams(window.location.search).get('run')||undefined);return()=>abort.current?.abort()},[load]);
  useEffect(()=>{const navigate=()=>{setView(views.find(v=>v.id===window.location.hash.slice(1))?.id||'overview');setMobile(false)};window.addEventListener('hashchange',navigate);return()=>window.removeEventListener('hashchange',navigate)},[]);
  const onView=useCallback((id:string)=>{setView(id);window.location.hash=id;setMobile(false);setTimeout(()=>heading.current?.focus(),0)},[]);
  const onVessel=useCallback((id:string)=>setSelected(id),[]);const onPort=useCallback((id:string)=>setPort(id),[]);
  async function perform<T>(label:string,fn:()=>Promise<T>):Promise<T|undefined>{setAction(label);setError(null);setMessage(null);try{const result=await fn();setMessage(label==='Scenario'?'Scenario solved. Results persisted; operational data remains unchanged.':`${label} completed.`);return result}catch(e){setError(e instanceof Error?e.message:'Action failed');return undefined}finally{setAction(null)}}
  async function transition(kind:'review'|'approve'){if(!data?.run.plan)return;const id=data.run.id;await perform(kind==='review'?'Review':'Approval',async()=>{await request<Plan>(`/plans/${data.run.plan!.id}/${kind}`,{actor:actor.trim(),expected_revision:data.run.plan!.revision});await load(id)})}
  async function draft(){if(!data)return;await perform('Operational draft',async()=>{const run=await request<Run>('/optimisation/run',{as_of:data.run.as_of,port_ids:data.inventory.routing_ports.map(p=>p.id),predictor:'auto',time_limit_seconds:3});await load(run.id);onView('shifts')})}
  const busy=loading||!!action,current=views.find(v=>v.id===view)!;
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to operations content</a><aside className={`sidebar ${mobile?'mobile-open':''}`}><a href="#overview" className="brand" onClick={e=>{e.preventDefault();onView('overview')}}><img className="brand-logo" src="/quay-logo.png" alt="QUAY project logo"/><span><strong>QUAY<span className="brand-period">.</span></strong><small>OPERATIONS INTELLIGENCE</small></span></a><div className="workspace-label">CONTROL CENTRE <span>72H</span></div><nav aria-label="Operations views">{views.map(v=><button key={v.id} className={view===v.id?'active':''} aria-current={view===v.id?'page':undefined} onClick={()=>onView(v.id)}><v.icon size={18}/><span>{v.label}</span>{view===v.id&&<span className="nav-active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-status"><Activity size={17}/><span>Evidence, before action<small>Models predict. Operators decide.</small></span></div><a className="docs-link" href={API_BASE.replace(/\/api\/v1$/,'')+'/docs'} target="_blank" rel="noreferrer">API documentation <ArrowUpRight size={14}/></a>{presentation&&<a className="docs-link" href="/demo-backup/index.html" target="_blank" rel="noreferrer">Demo guide & offline backup <ArrowUpRight size={14}/></a>}<div className="supervisor-profile"><span className="avatar">DS</span><span><strong>Demo workspace</strong><small>Local decision support</small></span><Waves size={19}/></div></div></aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Toggle navigation" onClick={()=>setMobile(!mobile)}><Menu size={21}/></button><Compass size={18}/><span>Operations control</span><span className="breadcrumb-slash">/</span><strong>{current.short}</strong></div><div className="topbar-right"><OperatorAccess onAuthenticated={()=>load(data?.run.id||new URLSearchParams(window.location.search).get('run')||undefined)}/><span className="api-status"><span className="status-dot"/>{view==='historical'?'Replay endpoint':loading?'Loading API':loadFailed?'API unavailable':data?'API connected':'API unavailable'}</span><button className="icon-button" aria-label="Refresh dashboard" disabled={busy} onClick={()=>load(data?.run.id)}><RefreshCw size={17} className={loading?'spin':''}/></button><button className="icon-button" aria-label="Open supervisor alerts" onClick={()=>onView('shifts')}><Bell size={18}/>{data&&data.alerts.some(a=>a.state==='OPEN')&&<span className="notification-dot"/>}</button><span className="avatar small">DS</span></div></header>
    <main id="main-content" aria-busy={busy}><div className="page-heading"><div><p className="eyebrow">{data?.run.scenario_id?'SCENARIO WORKSPACE':'PORT OPERATIONS'} <span className="heading-dot">/</span> {data?`${utc(data.run.as_of,true)} UTC`:'72-HOUR DECISION HORIZON'}</p><h1 ref={heading} tabIndex={-1}>{current.label}</h1><p>{({overview:'The network at a glance. The next move in focus.',heatmap:'Know where pressure builds before vessels start queuing.',timeline:'Turn shared resources into an executable schedule.',map:'Port capacity, vessel approaches and responsible alternatives.',shifts:'Nine shifts. Clear responsibilities. No surprises at handover.',scenario:'Explore the operational impact before changing the plan.',copilot:'Ask why. Inspect the evidence. Keep operational control.',live:'Persist events. Detect changed risks. Replan with operational safeguards.',historical:'Replay the September 2021 LA/LB crisis with a strict information cutoff.',evaluation:'Inspect measured trade-offs across three synthetic stress scenarios.'} as Record<string,string>)[view]}</p></div>{data&&view!=='historical'&&<div className="page-filters"><label>Port scope<select aria-label="Port scope" value={port} onChange={e=>setPort(e.target.value)} disabled={busy}><option value="all">All ports</option>{data.inventory.routing_ports.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Persisted plan / scenario<select aria-label="Persisted plan or scenario" value={data.run.id} onChange={e=>load(e.target.value)} disabled={busy}>{data.choices.map(c=><option key={c.id} value={c.id}>{c.name} · {c.plan_status||'No plan'} · {c.id.slice(0,6)}</option>)}</select></label></div>}</div>
    {error&&view!=='historical'&&<div className="error-banner" role="alert"><TriangleAlert size={19}/><span><strong>Unable to complete the request</strong>{error}{loadFailed&&data&&<small>Showing previously loaded run {data.run.id} at {utc(data.run.as_of,true)} UTC. Refresh failed.</small>}</span><button className="button secondary" disabled={busy} onClick={()=>load(data?.run.id)}>Retry loading</button></div>}{message&&<div className="success-banner" role="status">{message}<button aria-label="Dismiss status" className="icon-button" onClick={()=>setMessage(null)}><X size={15}/></button></div>}{action&&<div className="action-status" role="status"><LoaderCircle size={16} className="spin"/>{action} in progress. Forecasting and solver preprocessing may take up to a minute.</div>}
    {view==='historical'?<Suspense fallback={<Loading/>}><HistoricalReplay/></Suspense>:!data?loading?<Loading/>:<div className="loading"><Ship size={35}/><h2>{error?.includes('Operator access required')?'Unlock the operations workspace':'Your workspace is not ready'}</h2><p>{error?.includes('Operator access required')?'Open Operator access in the header and enter the local demo key printed by the launcher.':'Check the backend connection and run the dashboard seed command documented in README.'}</p></div>:<><div className="scenario-strip"><span className="scenario-strip-icon"><FlaskConical size={16}/></span><strong>{data.scenario_name}</strong><span>{data.run.scenario_id?'HYPOTHETICAL':'OPERATIONAL'}</span><Badge level={data.run.plan?.document.confidence+' CONFIDENCE'}/></div>
      {demoId&&<div className="context-notice live-global-notice" role="status"><Activity size={18}/><span>Isolated live demo · {live.session?utc(live.session.clock,true)+' UTC':'Connecting'} · {live.connection} · {live.events[0]?.status||'Ready'} · Revised plans require operator approval.</span><button className="text-action" onClick={()=>onView('live')}>Inspect live events</button></div>}
      <Suspense fallback={<Loading/>}>{view==='evaluation'&&<Evaluation/>}{view==='live'&&<LiveOperations data={data} port={port} live={live} onAttach={attach} onLeave={leave} onReview={()=>transition('review')} onApprove={()=>transition('approve')} busy={busy}/>} {view==='copilot'&&<Copilot data={data} port={port} busy={busy}/>} {view==='overview'&&<>{presentation&&<DemoObservations data={data} port={port}/>}<Overview data={data} port={port} onView={onView} onVessel={onVessel}/></>}{view==='heatmap'&&<Heatmap data={data} port={port} loading={loading}/>}{view==='timeline'&&<Timeline data={data} port={port} onVessel={onVessel}/>}{view==='map'&&<PortMap data={data} port={port} onVessel={onVessel} onPort={onPort}/>}{view==='shifts'&&<Shifts data={data} port={port} busy={busy} actor={actor} setActor={setActor} onReview={()=>transition('review')} onApprove={()=>transition('approve')} onDraft={draft} onExport={format=>perform('Export',()=>downloadPlan(data.run.plan!.id,format))} onAck={(id,revision)=>perform('Acknowledgement',async()=>{await request(`/alerts/${id}/acknowledge`,{actor:actor.trim(),expected_revision:revision});await load(data.run.id)})} onVessel={onVessel}/>}{view==='scenario'&&<Scenario data={data} port={port} busy={busy} onSimulate={body=>perform('Scenario',async()=>{const run=await request<Run>('/dashboard/scenarios',body);await load(run.id);return run})}/>} 
      </Suspense>
      <footer className="workspace-footer"><span><Activity size={13}/>Decision support. Operator judgement required.</span><details><summary>Data provenance & assumptions <ChevronDown size={12}/></summary><ReasonList items={data.notices}/><small>Model: {data.run.plan?.document.model_version||'Unavailable'} · Source: {data.run.id}</small></details></footer>
    </>}
    </main></div>{selected&&data&&<VesselDetail key={selected} data={data} id={selected} onClose={()=>setSelected(null)}/>}
  </div>
}
