import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';

const out='artifacts/dashboard';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
await context.tracing.start({screenshots:true,snapshots:true,sources:true});
const page=await context.newPage(),record={steps:[],requests:[],errors:[],exports:[]};
page.on('pageerror',e=>record.errors.push(e.message));
page.on('response',async r=>{if(r.request().method()==='POST'&&r.url().includes('/api/'))record.requests.push({url:r.url(),status:r.status(),body:r.request().postDataJSON()})});
const nav=async(name)=>{await page.getByRole('navigation').getByRole('button',{name,exact:true}).click();await page.getByRole('heading',{level:1,name,exact:true}).waitFor();};
const step=s=>{record.steps.push(s);console.log(s)};
async function exportPlan(label,name){const promise=page.waitForEvent('download');await page.getByRole('button',{name:label,exact:true}).click();const download=await promise;await download.saveAs(`${out}/${name}`);record.exports.push({name,suggestedFilename:download.suggestedFilename()});return fs.readFile(`${out}/${name}`,'utf8')}
try{
  await page.goto('http://127.0.0.1:5173');await page.locator('.command-banner').waitFor({timeout:120000});
  record.sourceRun=new URL(page.url()).searchParams.get('run');await expect(page.locator('.scenario-strip')).toContainText('Storm');step('Default Storm + Crane Breakdown loaded from persisted backend data.');
  await page.locator('.vessel-link').first().click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog')).toContainText('Uncertainty band');await page.keyboard.press('Escape');step('Vessel prediction, crane schedule and routing evidence inspected.');
  await nav('Congestion heatmap');await page.locator('.heat-cell').first().click();await page.keyboard.press('ArrowRight');await expect(page.locator('.forecast-detail')).toBeVisible();step('72-hour hierarchical heatmap inspected with keyboard focus and forecast causes.');
  await nav('Berth planning');await page.getByRole('button',{name:'Current / FCFS',exact:true}).click();await expect(page.getByRole('button',{name:'Current / FCFS',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Optimised',exact:true}).click();await page.locator('.vessel-block').first().click();await expect(page.getByRole('dialog')).toContainText('Timed crane segments');await page.keyboard.press('Escape');step('Baseline and optimised Gantt schedules and crane profiles inspected.');
  await nav('Port network map');await page.locator('.leaflet-container').waitFor();const route=await page.getByLabel('Vessel map route').locator('option').nth(1).getAttribute('value');await page.getByLabel('Vessel map route').selectOption(route);await page.locator('.port-card').first().click();await expect(page.getByLabel('Port scope')).toHaveValue('P01');step('Real port coordinates, selectable illustrative approach and port scope inspected.');
  await page.getByLabel('Port scope').selectOption('all');await nav('Supervisor shift plan');await expect(page.getByRole('button',{name:'Approve plan'})).toBeDisabled();const tabs=page.getByRole('tab');await expect(tabs).toHaveCount(9);await tabs.nth(8).click();await page.keyboard.press('Home');await expect(tabs.first()).toHaveAttribute('aria-selected','true');
  const initial=JSON.parse(await exportPlan('JSON','scenario-plan.json'));record.scenarioExportState=initial.status;await exportPlan('CSV','scenario-plan.csv');await exportPlan('Printable HTML','scenario-plan.html');step('Nine shifts, handover notes and real JSON/CSV/printable HTML exports verified; hypothetical approval disabled.');
  const ack=page.getByRole('button',{name:'Acknowledge',exact:true});if(await ack.count()){await ack.first().click();await expect(page.locator('.success-banner')).toBeVisible({timeout:120000});step('Forecast alert acknowledged through revision-checked backend lifecycle.');}
  await nav('Scenario simulator');await page.getByLabel('Port scope').selectOption('P01');
  for(const [label,value] of [['Arrival surge',50],['Weather severity',2],['Yard capacity',90]]){await page.getByRole('slider',{name:label,exact:true}).fill(String(value));}
  const crane=await page.getByLabel('Crane outage selector').locator('option').nth(1).getAttribute('value');await page.getByLabel('Crane outage selector').selectOption(crane);
  const response=page.waitForResponse(r=>r.url().endsWith('/dashboard/scenarios')&&r.request().method()==='POST',{timeout:180000});await page.getByRole('button',{name:'Run Scenario',exact:true}).click();const solved=await response;record.scenarioStatus=solved.status();record.scenario=await solved.json();expect(solved.ok()).toBeTruthy();await expect(page.locator('.comparison-table')).toBeVisible({timeout:180000});await page.screenshot({path:`${out}/scenario-after.png`,fullPage:true});step('Arrival compression, storm closure, yard adjustment and selected crane outage solved and persisted; before/after uses actual solver output.');
  await page.getByLabel('Port scope').selectOption('P04');await nav('Supervisor shift plan');
  const draftResponse=page.waitForResponse(r=>r.url().endsWith('/optimisation/run')&&r.request().method()==='POST',{timeout:180000});await page.getByRole('button',{name:/Create operational draft/}).click();const draft=await draftResponse;record.draft=await draft.json();expect(draft.ok()).toBeTruthy();await expect(page.getByRole('button',{name:'Mark reviewed'})).toBeEnabled({timeout:180000});expect(record.draft.metrics.deferred_vessels).toBe(0);
  await page.getByLabel('Supervisor name').fill('Browser walkthrough supervisor');await page.getByRole('button',{name:'Mark reviewed'}).click();await expect(page.getByRole('button',{name:'Approve plan'})).toBeEnabled({timeout:120000});await page.getByRole('button',{name:'Approve plan'}).click();await expect(page.locator('.plan-meta')).toContainText('Revision 3',{timeout:120000});
  const approved=JSON.parse(await exportPlan('JSON','approved-plan.json'));record.approvedExportState=approved.status;expect(approved.status).toBe('APPROVED');expect(approved.shifts).toHaveLength(9);await exportPlan('CSV','approved-plan.csv');await exportPlan('Printable HTML','approved-plan.html');await page.screenshot({path:`${out}/approved-plan.png`,fullPage:true});step('Operational draft created for P04, reviewed at revision 1 and approved at revision 2; all three exports preserve APPROVED revision 3 and nine shifts.');
  await nav('Executive overview');await nav('Congestion heatmap');await page.goBack();await expect(page.getByRole('heading',{level:1,name:'Executive overview',exact:true})).toBeVisible();step('Browser back navigation preserves the working view.');
  const docs=await context.request.get('http://127.0.0.1:5173/openapi.json');expect(docs.ok()).toBeTruthy();record.openapiPaths=Object.keys((await docs.json()).paths).length;
  expect(record.errors).toEqual([]);record.result='PASS';
}catch(e){record.result='FAIL';record.failure=String(e);await page.screenshot({path:`${out}/failure.png`,fullPage:true});console.error(e);process.exitCode=1}
finally{await context.tracing.stop({path:`${out}/browser-trace.zip`});await fs.writeFile(`${out}/journey.json`,JSON.stringify(record,null,2));await browser.close()}
