import {ArrowRight,Clock3,Ship,Anchor,Construction,Warehouse,TrendingDown,Leaf,Wallet,TriangleAlert} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import type {Dashboard} from '../types';
import {callName,currentRows,mean,money,number,outlook,queueHours,utc,worst} from '../selectors';
import {Badge,Empty,Panel,TextAction} from './Primitives';

function HarbourArt(){return <svg className="harbour-art" viewBox="0 0 440 190" aria-hidden="true"><defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" fill="none" stroke="#fff" strokeOpacity=".06"/></pattern></defs><rect width="440" height="190" fill="url(#grid)"/><path d="M0 167H440M0 183H440" stroke="#75b6c4" strokeOpacity=".25"/><g fill="none" stroke="#899fae" strokeWidth="3"><path d="M107 146V37L230 20V44H89M107 58L145 146M183 26V113M280 147V62L402 39V65H261M280 84L313 147M360 47V113"/><path d="M94 146H156M266 147H325"/></g><path d="M85 130H330L310 160H105Z" fill="#293e50" stroke="#94b7c6"/><path d="M110 122V104H155V125M250 125V99H296V125" fill="#d07840"/><path d="M158 125V103H202V125M205 125V102H246V125" fill="#527b8b"/><path d="M174 100V79H217V100M219 100V79H262V100" fill="#738b98"/><path d="M286 99V78H315V131H296" fill="#ccd6da"/><path d="M301 78V66H307V78" stroke="#a7b5ba" strokeWidth="3"/><circle cx="183" cy="113" r="4" fill="#ff9a52"/><circle cx="360" cy="113" r="4" fill="#ff9a52"/><path d="M12 171H74M172 175H251M336 171H416" stroke="#65b1c2" strokeOpacity=".55"/></svg>}

export function Overview({data,port,onView,onVessel}:{data:Dashboard;port:string;onView:(v:string)=>void;onVessel:(id:string)=>void}){
  const rows=currentRows(data,port);const series=outlook(data,port);
  const waiting=data.waiting_predictions.filter(p=>port==='all'||p.port_id===port);
  const atRisk=waiting.filter(p=>p.prediction>data.risk_wait_threshold_hours).sort((a,b)=>b.prediction-a.prediction);
  const hotspot=data.forecast_rows.filter(r=>r.scope==='port'&&r.is_hotspot&&(port==='all'||r.port_id===port)).sort((a,b)=>a.timestamp.localeCompare(b.timestamp))[0];
  const comparison=data.run.comparison;
  const scheduleValid=data.run.status==='succeeded'&&data.run.metrics?.validation_passed!==false;
  const b=scheduleValid?comparison?.baseline:undefined,o=scheduleValid?comparison?.optimised:undefined;
  const cards=[{label:'Congestion status',value:worst(rows),sub:'At the recorded forecast origin',icon:TriangleAlert,badge:true},
    {label:'Vessels at risk',value:waiting.length?number(atRisk.length,0):'?',sub:`Predicted wait exceeds ${number(data.risk_wait_threshold_hours)} hours`,icon:Ship},
    {label:'Predicted vessel wait',value:`${number(mean(waiting.map(p=>p.prediction)))} h`,sub:'Mean across scheduled predictions',icon:Clock3},
    {label:'Berth utilisation',value:rows.length?`${number(mean(rows.map(r=>r.berth_utilisation))!*100,0)}%`:'—',sub:'Mean of selected port projections',icon:Anchor},
    {label:'Crane utilisation',value:rows.length?`${number(mean(rows.map(r=>r.crane_utilisation))!*100,0)}%`:'—',sub:'Available crane capacity in use',icon:Construction},
    {label:'Yard occupancy',value:rows.length?`${number(mean(rows.map(r=>r.yard_occupancy))!*100,0)}%`:'—',sub:'Mean of selected port projections',icon:Warehouse}];
  return <><section className="command-banner"><div><span className="banner-tag"><span className="status-dot"/>{data.run.scenario_id?'SCENARIO INTELLIGENCE':'OPERATIONAL INTELLIGENCE'}</span><h2>See the pressure.<br/>Stay ahead of the queue.</h2><p>One network. A clear view of the next 72 hours.</p><button className="banner-button" onClick={()=>onView('heatmap')}>Explore congestion outlook <ArrowRight size={17}/></button></div><HarbourArt/><div className="banner-insight"><span className="eyebrow">NEXT EXPECTED HOTSPOT</span><strong>{hotspot?data.inventory.routing_ports.find(p=>p.id===hotspot.port_id)?.name:(data.forecast_rows.length?'No hotspot predicted':'Forecast unavailable')}</strong><span>{hotspot?`${utc(hotspot.timestamp,true)} UTC · ${hotspot.expected_hotspot_duration_hours}h episode`:'Within the recorded 72-hour horizon'}</span>{hotspot&&<Badge level={hotspot.congestion_severity}/>}</div></section>
    <div className="kpi-grid">{cards.map(c=><article className="kpi" key={c.label}><div className="kpi-label"><span>{c.label}</span><c.icon size={17}/></div>{c.badge?<div className="kpi-value"><Badge level={c.value}/></div>:<strong className="kpi-value">{c.value}</strong>}<small>{c.sub}</small></article>)}</div>
    <div className="overview-grid"><Panel title="Pressure on the horizon" eyebrow="72-HOUR FORECAST" action={<span className="model-chip">MODEL + RESOURCE PROJECTION</span>}>
      {series.length?<><div className="chart-key"><span><i className="key-dot teal"/>Mean congestion probability</span><span><i className="key-dot orange"/>Projected queue wait</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={series} margin={{top:15,right:6,left:-12,bottom:5}} accessibilityLayer><defs><linearGradient id="pressure" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#23888c" stopOpacity={.25}/><stop offset="100%" stopColor="#23888c" stopOpacity={.02}/></linearGradient></defs><CartesianGrid stroke="#e9edf1" vertical={false}/><XAxis dataKey="timestamp" tickFormatter={v=>utc(v,true)} minTickGap={65} tick={{fontSize:10,fill:'#586b7c'}} axisLine={false} tickLine={false}/><YAxis yAxisId="prob" domain={[0,100]} tickFormatter={v=>`${v}%`} tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis yAxisId="wait" orientation="right" tickFormatter={v=>`${v}h`} tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={v=>`${utc(String(v),true)} UTC`} formatter={(value,name)=>[`${number(Number(value))}${name==='probability'?'%':' h'}`,name==='probability'?'Congestion probability':'Projected wait']} contentStyle={{borderRadius:10,fontSize:12}}/><Area yAxisId="prob" type="monotone" dataKey="probability" stroke="#23888c" fill="url(#pressure)" strokeWidth={2} isAnimationActive={false}/><Area yAxisId="wait" type="monotone" dataKey="wait" stroke="#dc894c" fill="transparent" strokeWidth={2} strokeDasharray="4 4" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><p className="panel-footnote">Hourly buckets · UTC · LOW synthetic confidence · berth probabilities inherit terminal priors</p></>:<Empty>No trained outlook available for this run.</Empty>}
    </Panel><Panel title="The value of a better plan" eyebrow="FCFS → OPTIMISED · FULL RUN SCOPE">
      {b&&o?<><div className="savings-item"><span className="savings-icon"><TrendingDown size={19}/></span><div><strong>{number(queueHours(b)-queueHours(o),0)} <small>hours</small></strong><p>Queue-hours proxy avoided</p></div></div><div className="savings-item"><span className="savings-icon"><Wallet size={19}/></span><div><strong>{money(comparison.estimated_cost_savings_usd)}</strong><p>Estimated planning cost saved</p></div></div><div className="savings-item"><span className="savings-icon"><Leaf size={19}/></span><div><strong>{number(comparison.estimated_emissions_savings_tonnes_co2)} <small>t CO₂</small></strong><p>Waiting and sailing emissions proxy</p></div></div><p className="panel-footnote">Modelled gains, including deferral wait proxies. Not realised savings.</p></>:<Empty>No schedule comparison available.</Empty>}
    </Panel></div>
    <div className="overview-grid bottom-grid"><Panel title="Vessels needing your attention" eyebrow={`${atRisk.length} AT RISK IN SELECTED SCOPE`} action={<TextAction onClick={()=>onView('timeline')}>Open berth planner</TextAction>}>
      <div className="table-scroll"><table><thead><tr><th>Vessel / call</th><th>ETA · UTC</th><th>Predicted wait</th><th>Uncertainty band</th><th>Priority</th></tr></thead><tbody>{atRisk.slice(0,5).map(p=>{const c=data.inventory.calls.find(c=>c.id===p.call_id);return <tr key={p.call_id}><td><button className="vessel-link" onClick={()=>onVessel(p.call_id)}>{callName(data,p.call_id)}</button><small className="subline">{p.call_id}</small></td><td>{c?utc(c.scheduled_eta,true):'—'}</td><td><strong className="risk-number">{number(p.prediction)} h</strong></td><td>{number(p.lower)}–{number(p.upper)} h</td><td><span className="priority-tag">P{c?.priority}</span></td></tr>})}</tbody></table></div>{!atRisk.length&&<Empty>{waiting.length?'No vessels exceed the configured waiting-time threshold.':'No waiting predictions available for this run and scope.'}</Empty>}
    </Panel><Panel title="Current vs optimised" eyebrow="FIRST-COME-FIRST-SERVED BASELINE">
      {b&&o?<><table className="comparison-table"><thead><tr><th>Metric</th><th>FCFS</th><th>Optimised</th></tr></thead><tbody>{[['Served mean wait',`${number(b.average_wait_hours)} h`,`${number(o.average_wait_hours)} h`],['Maximum wait',`${number(b.maximum_wait_hours)} h`,`${number(o.maximum_wait_hours)} h`],['Deferred vessels',number(b.deferred_vessels,0),number(o.deferred_vessels,0)],['Berth utilisation',`${number(b.berth_utilisation*100,0)}%`,`${number(o.berth_utilisation*100,0)}%`],['Planning cost',money(b.estimated_cost_usd),money(o.estimated_cost_usd)]].map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table><div className="solver-note"><span className="status-dot"/>{data.run.solver_status} · {number(data.run.solver_runtime_ms/1000)}s solver runtime</div>{!comparison.same_served_vessels&&<p className="panel-footnote">Served sets differ; compare deferrals and total queue-hours proxy alongside served waits.</p>}</>:<Empty>No comparison available.</Empty>}
    </Panel></div>
  </>;
}
