import {useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import type {Dashboard} from '../types';
import {callName,currentRows,number,worst} from '../selectors';
import {Badge,Empty,Panel} from './Primitives';
const COLORS={LOW:'#289da0',MEDIUM:'#d3922c',HIGH:'#df6750',CRITICAL:'#ad3158',UNAVAILABLE:'#687582'};
export function PortMap({data,port,onVessel,onPort}:{data:Dashboard;port:string;onVessel:(id:string)=>void;onPort:(id:string)=>void}){
  const node=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null);const [vessel,setVessel]=useState(''),[tileError,setTileError]=useState(false);
  useEffect(()=>{if(!node.current)return;const m=L.map(node.current,{scrollWheelZoom:false,minZoom:1}).setView([20,0],2);map.current=m;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>setTileError(true)).addTo(m);const resize=new ResizeObserver(()=>m.invalidateSize());resize.observe(node.current);return()=>{resize.disconnect();m.remove();map.current=null}},[]);
  useEffect(()=>{const m=map.current;if(!m)return;const group=L.layerGroup().addTo(m);data.inventory.routing_ports.forEach(p=>{const severity=worst(currentRows(data,p.id))||'UNAVAILABLE';const marker=L.circleMarker([p.latitude,p.longitude],{radius:p.id===port?13:10,color:'#fff',weight:2,fillColor:COLORS[severity],fillOpacity:1}).addTo(group);const label=document.createElement('span');label.textContent=`${p.name} · ${severity}`;marker.bindTooltip(label,{direction:'top'}).on('click',()=>onPort(p.id))});const lines=vessel?data.routes.filter(r=>r.call_id===vessel):data.routes.filter(r=>port==='all'||r.port_id===port).slice(0,8);lines.forEach(r=>{const line=L.polyline(r.coordinates,{color:vessel?'#ed924f':'#61a9b4',weight:vessel?3:1.5,opacity:vessel?1:.6,dashArray:'5 7'}).addTo(group);const text=document.createElement('span');text.textContent=`${callName(data,r.call_id)} · ${r.remaining_distance_nm.toFixed(0)}nm · ${r.basis}`;line.bindTooltip(text).on('click',()=>onVessel(r.call_id))});data.recommendations.filter(r=>r.recommended_action==='ALTERNATE_PORT').forEach(r=>{const terminal=data.inventory.terminals.find(t=>t.id===r.recommended_plan_outcome?.terminal_id),destination=data.inventory.routing_ports.find(p=>p.id===terminal?.port_id),origin=data.inventory.routing_ports.find(p=>p.id===r.port_id);if(destination&&origin){L.polyline([[origin.latitude,origin.longitude],[destination.latitude,destination.longitude]],{color:'#dc8b43',dashArray:'8 8'}).addTo(group).on('click',()=>onVessel(r.call_id))}});const selected=data.inventory.routing_ports.find(p=>p.id===port);if(selected)m.setView([selected.latitude,selected.longitude],5);else m.fitBounds(L.latLngBounds(data.inventory.routing_ports.map(p=>[p.latitude,p.longitude] as [number,number])),{padding:[35,35],maxZoom:3});return()=>{group.remove()}},[data,port,vessel,onPort,onVessel]);
  const selected=data.inventory.routing_ports.find(p=>p.id===port);const rows=currentRows(data,port);
  return <><Panel title="A connected view of the coast" eyebrow="PORT NETWORK & ROUTING EVIDENCE" action={<label className="compact-label">Approach route<select aria-label="Vessel map route" value={vessel} onChange={e=>setVessel(e.target.value)}><option value="">Network approaches</option>{data.routes.filter(r=>port==='all'||r.port_id===port).map(r=><option key={r.call_id} value={r.call_id}>{callName(data,r.call_id)} · {r.call_id}</option>)}</select></label>}>
    <div className="map-wrap"><div className="port-map" ref={node} role="region" aria-label="Interactive OpenStreetMap port network"/>{tileError&&<div className="map-notice" role="status">Some map tiles are unavailable. Port markers and supplied routes remain selectable.</div>}<div className="map-caption">ILLUSTRATIVE VESSEL APPROACHES · NOT LIVE AIS</div></div><div className="map-port-grid">{data.inventory.routing_ports.map(p=><button className={`port-card ${port===p.id?'selected':''}`} onClick={()=>onPort(p.id)} key={p.id}><span className="eyebrow">{p.id} · {number(p.latitude,2)}°, {number(p.longitude,2)}°</span><strong>{p.name}</strong><Badge level={worst(currentRows(data,p.id))}/></button>)}</div><p className="panel-footnote">Approach bearings are declared synthetic assumptions; voyage distances come from audited backend inputs. Lines are illustrations, not navigation or observed vessel positions.</p>
    {selected&&<div className="detail-stats"><span>{selected.name}</span><span>Projected queue <strong>{number(rows[0]?.queue_length)}</strong></span><span>Projected wait <strong>{number(rows[0]?.average_wait_hours)}h</strong></span><span>Confidence <strong>{rows[0]?.confidence_level||'Unavailable'}</strong></span></div>}
  </Panel><Panel title="Responsible alternatives" eyebrow="END-TO-END BENEFIT, NOT CONGESTION ALONE"><div className="recommendation-grid">{data.recommendations.filter(r=>r.recommended_action!=='KEEP_CURRENT_PLAN'&&(port==='all'||r.port_id===port)).map(r=><button className="recommendation-card" onClick={()=>onVessel(r.call_id)} key={r.id}><span className="eyebrow">{r.recommended_action.replaceAll('_',' ')}</span><strong>{callName(data,r.call_id)}</strong><span>{number(r.expected_hours_saved)}h delivery gain · {r.confidence_level} confidence</span><span className="expiry-note">{r.is_expired?'Expired historical what-if':'Requires operator approval'}</span></button>)}</div>{!data.recommendations.some(r=>r.recommended_action!=='KEEP_CURRENT_PLAN'&&(port==='all'||r.port_id===port))&&<Empty>No beneficial alternate action in this scope.</Empty>}<p className="panel-footnote">Globally separated demo ports correctly produce no justified cross-port diversions. Open a vessel for rejection reasons, costs, uncertainty and expiry.</p></Panel></>
}
