import {useEffect,useState} from 'react';
import {FlaskConical,Play,RotateCcw} from 'lucide-react';
import type {Dashboard,Metrics,Run} from '../types';
import {money,number,utc} from '../selectors';
import {Badge,Panel} from './Primitives';
export function Scenario({data,port,busy,onSimulate}:{data:Dashboard;port:string;busy:boolean;onSimulate:(body:unknown)=>Promise<Run|undefined>}){
  const [surge,setSurge]=useState(0),[weather,setWeather]=useState(3),[yard,setYard]=useState(100),[outage,setOutage]=useState(8),[cranes,setCranes]=useState<string[]>([]),[before,setBefore]=useState<Metrics|null>(null),[after,setAfter]=useState<Run|null>(null);
  const available=data.inventory.cranes.filter(c=>port==='all'||data.inventory.terminals.find(t=>t.id===data.inventory.berths.find(b=>b.id===c.berth_id)?.terminal_id)?.port_id===port);
  useEffect(()=>{setCranes(old=>old.filter(id=>available.some(c=>c.id===id)))},[port]);
  async function run(){const original=data.run.metrics;const result=await onSimulate({source_run_id:data.run.id,port_id:port==='all'?null:port,arrival_compression_pct:surge,crane_ids:cranes,outage_hours:outage,weather_severity:weather,yard_capacity_pct:yard,time_limit_seconds:3});if(result){setBefore(original);setAfter(result)}}
  const b=before||data.run.metrics,a=after?.metrics;
  return <div className="scenario-layout"><Panel title="Test the conditions. See the consequences." eyebrow="SCENARIO LAB · HYPOTHETICAL ONLY"><div className="scenario-intro"><FlaskConical size={23}/><p>Adjust known capacity and scheduled demand. The backend recomputes forecasts and solves the scenario without applying operational changes.</p></div>
    <div className="scenario-control"><label htmlFor="surge">Arrival surge <strong>{surge}% compression</strong></label><input id="surge" aria-label="Arrival surge" type="range" min="0" max="100" step="5" value={surge} onChange={e=>setSurge(Number(e.target.value))}/><p>Compress unstarted arrivals after +6h toward the same arrival window. Original source conditions are retained.</p></div>
    <div className="scenario-control"><label htmlFor="weather">Weather severity <strong>{['Clear','Adverse','Severe','Shutdown'][weather]}</strong></label><input id="weather" aria-label="Weather severity" type="range" min="0" max="3" value={weather} onChange={e=>setWeather(Number(e.target.value))}/><p>{[0,4,8,16][weather]}h additional handling suspension, beginning at +8h. This models a storm closure, not a generated weather observation.</p></div>
    <div className="scenario-control"><label htmlFor="yard">Yard capacity <strong>{yard}% of physical capacity</strong></label><input id="yard" aria-label="Yard capacity" type="range" min="50" max="150" step="5" value={yard} onChange={e=>setYard(Number(e.target.value))}/><p>Temporary hypothetical capacity. The API rejects capacity below existing inventory.</p></div>
    <div className="scenario-control"><label htmlFor="crane-select">Crane outage selector</label><select id="crane-select" aria-label="Crane outage selector" value="" onChange={e=>{if(e.target.value&&!cranes.includes(e.target.value))setCranes([...cranes,e.target.value])}} disabled={cranes.length>=12}><option value="">Add a crane to the outage</option>{available.filter(c=>!cranes.includes(c.id)).map(c=><option value={c.id} key={c.id}>{c.id} · {c.productivity_moves_per_hour} moves/h inventory rate</option>)}</select><div className="selected-cranes">{cranes.map(id=><button key={id} onClick={()=>setCranes(cranes.filter(c=>c!==id))} aria-label={`Remove ${id}`}>{id} ×</button>)}</div><label className="inline-label">Outage duration <select aria-label="Outage duration" value={outage} onChange={e=>setOutage(Number(e.target.value))}>{[4,8,16,24,48].map(h=><option value={h} key={h}>{h} hours</option>)}</select></label></div>
    <div className="scenario-footer"><button className="button secondary" disabled={busy} onClick={()=>{setSurge(0);setWeather(0);setYard(100);setCranes([]);setBefore(null);setAfter(null)}}><RotateCcw size={15}/>Reset conditions</button><button className="button primary" disabled={busy} onClick={run}><Play size={15}/>{busy?'Solving scenario…':'Run Scenario'}</button></div>
  </Panel><Panel title="Before vs after" eyebrow="FULL RUN SCOPE · ACTUAL SOLVER RESULTS"><div className="scenario-source"><span className="eyebrow">SOURCE SNAPSHOT</span><strong>{utc(data.run.as_of,true)} UTC</strong><p>{port==='all'?'All ports':data.inventory.routing_ports.find(p=>p.id===port)?.name} · changes applied to selected scope</p></div>{a?<><Badge level={after!.solver_status}/><table className="comparison-table"><thead><tr><th>Metric</th><th>Before</th><th>After</th></tr></thead><tbody>{[['Mean served wait',`${number(b.average_wait_hours)}h`,`${number(a.average_wait_hours)}h`],['Maximum wait',`${number(b.maximum_wait_hours)}h`,`${number(a.maximum_wait_hours)}h`],['Deferred vessels',number(b.deferred_vessels,0),number(a.deferred_vessels,0)],['Berth utilisation',`${number(b.berth_utilisation*100)}%`,`${number(a.berth_utilisation*100)}%`],['Planning cost',money(b.estimated_cost_usd),money(a.estimated_cost_usd)],['Emissions proxy',`${number(b.estimated_emissions_tonnes_co2)}t`,`${number(a.estimated_emissions_tonnes_co2)}t`]].map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table><p className="panel-footnote">A scenario can increase delays or become infeasible. Unserved vessels remain explicit; served wait averages alone can hide deferrals.</p></>:<div className="scenario-empty"><FlaskConical size={36}/><h3>Your decisions, put to the test</h3><p>Run a scenario to compare actual capacity, waiting and economic proxy outcomes.</p></div>}<div className="scenario-caveat"><strong>Decision support, with guardrails</strong><p>Hypothetical runs remain read-only. Started work, compatibility and hard yard/crane limits are enforced. No LLM invents operational numbers.</p></div></Panel></div>
}
