import {useState} from 'react';
import {Ship,TriangleAlert} from 'lucide-react';
import type {Dashboard} from '../types';
import {callName,hours,number} from '../selectors';
import {Empty,Panel,ReasonList} from './Primitives';
export function Timeline({data,port,onVessel}:{data:Dashboard;port:string;onVessel:(id:string)=>void}){
  const [mode,setMode]=useState('optimised');const [localPort,setLocalPort]=useState(data.inventory.routing_ports[0]?.id||'');
  const pid=port==='all'?localPort:port;
  const berths=data.inventory.berths.filter(b=>data.inventory.terminals.find(t=>t.id===b.terminal_id)?.port_id===pid);
  const assignments=mode==='optimised'?data.effective_assignments:(data.run.comparison?.baseline_assignments||[]);
  const width=(start:number,end:number)=>({left:`${Math.max(0,start)/72*100}%`,width:`${Math.max(0,Math.min(72,end)-Math.max(0,start))/72*100}%`});
  return <Panel title="A berth for every move" eyebrow="72-HOUR BERTH & CRANE PLANNER" action={<div className="toolbar">{port==='all'&&<select aria-label="Timeline port" value={localPort} onChange={e=>setLocalPort(e.target.value)}>{data.inventory.routing_ports.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>}<div className="segmented"><button aria-pressed={mode==='baseline'} onClick={()=>setMode('baseline')}>Current / FCFS</button><button aria-pressed={mode==='optimised'} onClick={()=>setMode('optimised')}>Optimised</button></div></div>}>
    <div className="timeline-legend"><span><i className="arrival-key"/>Scheduled arrival</span><span><i className="waiting-key"/>Waiting</span><span><i className="berthing-key"/>Berthing / service</span><span><i className="departure-key"/>Departure buffer</span><span><i className="maintenance-key"/>Restriction</span><span><TriangleAlert size={13}/>Unassigned at ETA</span></div>
    {berths.length?<div className="timeline-scroll"><div className="timeline-grid"><div className="timeline-axis"><span className="berth-label">BERTH / CAPABILITY</span><div>{Array.from({length:10},(_,i)=><span style={{left:`${i/9*100}%`}} key={i}>+{i*8}h</span>)}</div></div>{berths.map(b=>{const jobs=assignments.filter(a=>a.berth_id===b.id);const conflicts=data.inventory.calls.filter(c=>data.run.diagnostics.unscheduled_call_ids.includes(c.id)&&c.terminal_id===b.terminal_id&&berths.find(x=>x.terminal_id===c.terminal_id)?.id===b.id);const cranes=new Set(data.inventory.cranes.filter(c=>c.berth_id===b.id).map(c=>c.id));const outages=data.inventory.availability.filter(a=>cranes.has(a.crane_id));return <div className="timeline-row" key={b.id}><div className="berth-label"><strong>{b.id}</strong><small>{number(b.length_m,0)}m · {number(b.depth_m)}m depth · ≤{b.max_cranes} cranes</small></div><div className="berth-track">{outages.map((a,i)=>{const start=hours(a.start,data.run.as_of),end=a.reason==='breakdown'?72:hours(a.end,data.run.as_of);return start<72&&end>0?<span className="outage-marker" style={width(start,end)} key={i} title={`${a.crane_id} · ${a.reason}. ${a.reason==='breakdown'?'Restoration unconfirmed; restriction persists.':a.start+' to '+a.end}`}/> :null})}{data.inventory.disruptions.filter(d=>d.kind==='storm'&&d.port_id===pid).map((d,i)=><span key={`storm-${i}`} className="storm-marker" style={width(hours(String(d.start),data.run.as_of),hours(String(d.end),data.run.as_of))} title={`Storm: ${d.start} to ${d.end}`}/>)}{mode==='optimised'&&conflicts.map(c=>{const eta=hours(c.scheduled_eta,data.run.as_of);return eta>=0&&eta<72?<button key={`conflict-${c.id}`} className="conflict-marker" style={{left:`${eta/72*100}%`}} onClick={()=>onVessel(c.id)} aria-label={`Unassigned vessel ${c.id}`} title={`${callName(data,c.id)}: unresolved allocation. Marker at scheduled ETA in requested terminal; no berth reserved.`}><TriangleAlert size={15}/></button>:null})}{jobs.map(a=>{const c=data.inventory.calls.find(c=>c.id===a.call_id);const eta=c?hours(c.scheduled_eta,data.run.as_of):0,start=hours(a.start,data.run.as_of),completion=hours(a.completion_time,data.run.as_of),end=hours(a.end,data.run.as_of);if(start>=72||end<=0)return null;const count=Math.max(0,...a.execution_profile.shift_cranes);return <div key={a.call_id}>{eta>=0&&eta<72&&<button className="arrival-marker" style={{left:`${eta/72*100}%`}} title={`${callName(data,a.call_id)} · ETA ${c?.scheduled_eta}`} aria-label={`Arrival details for ${a.call_id}`} onClick={()=>onVessel(a.call_id)}>◆</button>}{eta<start&&<button className="wait-block" style={width(Math.max(0,eta),start)} onClick={()=>onVessel(a.call_id)} title={`${a.call_id} · ${number(a.waiting_minutes/60)}h planned wait`} aria-label={`Waiting ${a.call_id}`}/>}
          <button className="vessel-block" style={width(start,completion)} onClick={()=>onVessel(a.call_id)} title={`${callName(data,a.call_id)} · ${a.call_id}\nStart ${a.start} · completion ${a.completion_time}\n${count} peak cranes · ${a.planned_moves} remaining moves`}><Ship size={12}/><span>{callName(data,a.call_id)}</span><small>{count}C</small>{end>72&&<span>→</span>}</button>{completion<72&&end>completion&&<button className="departure-block" style={width(completion,end)} onClick={()=>onVessel(a.call_id)} aria-label={`Departure ${a.call_id}`} title={`Departure ${a.end}`}/>}</div>})}</div></div>})}</div></div>:<Empty>No berth inventory in this scope.</Empty>}
    <p className="panel-footnote">Click a vessel for its crane segments and recommendation evidence. Bar widths include the full berth/service interval; productive segments are detailed in the vessel panel. Hatched restrictions can affect only part of a berth’s crane inventory.</p>
    <div className="conflict-strip"><TriangleAlert size={18}/><strong>{data.run.diagnostics.unscheduled_call_ids.length} unresolved vessel allocations · full run scope</strong></div><ReasonList items={data.run.diagnostics.infeasibility_explanations}/>
  </Panel>
}
