"""operational data and decision support

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from app.synthetic.storage import UTCInstant

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generator_version', sa.String(length=32), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('epoch', UTCInstant(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('as_of', UTCInstant(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('quality', sa.String(length=64), nullable=False),
    sa.Column('created_at', UTCInstant(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('horizon_hours = 72'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ports',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('as_of', UTCInstant(), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCInstant(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=False),
    sa.Column('epoch', UTCInstant(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessels',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('size_class', sa.String(length=160), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('draft_m', sa.Float(), nullable=False),
    sa.Column('capacity_teu', sa.Integer(), nullable=False),
    sa.Column('required_equipment', sa.String(length=160), nullable=False),
    sa.Column('max_cranes', sa.Integer(), nullable=False),
    sa.CheckConstraint("required_equipment IN ('panamax_sts','super_post_panamax_sts')"),
    sa.CheckConstraint("size_class IN ('feeder','panamax','ultra_large')"),
    sa.CheckConstraint('capacity_teu >= 0'),
    sa.CheckConstraint('draft_m >= 0'),
    sa.CheckConstraint('length_m >= 0'),
    sa.CheckConstraint('max_cranes >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimisation_runs',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('forecast_run_id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=160), nullable=True),
    sa.Column('as_of', UTCInstant(), nullable=False),
    sa.Column('end', UTCInstant(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('solver_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCInstant(), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('diagnostics', sa.JSON(), nullable=False),
    sa.CheckConstraint('"end" > as_of AND runtime_ms >= 0'),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminals',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('port_id', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('yard_capacity_teu', sa.Float(), nullable=False),
    sa.Column('initial_yard_teu', sa.Float(), nullable=False),
    sa.Column('gate_capacity_teu_per_hour', sa.Float(), nullable=False),
    sa.CheckConstraint('gate_capacity_teu_per_hour >= 0'),
    sa.CheckConstraint('initial_yard_teu <= yard_capacity_teu AND yard_capacity_teu > 0'),
    sa.CheckConstraint('initial_yard_teu >= 0'),
    sa.CheckConstraint('yard_capacity_teu >= 0'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tides',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('port_id', sa.String(length=160), nullable=False),
    sa.Column('timestamp', UTCInstant(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_id', 'timestamp')
    )
    op.create_index('ix_tides_lookup', 'tides', ['port_id', 'timestamp'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('port_id', sa.String(length=160), nullable=False),
    sa.Column('timestamp', UTCInstant(), nullable=False),
    sa.Column('period', sa.String(length=160), nullable=False),
    sa.Column('wind_mps', sa.Float(), nullable=False),
    sa.Column('rain_mm_per_hour', sa.Float(), nullable=False),
    sa.Column('visibility_m', sa.Float(), nullable=False),
    sa.CheckConstraint("period IN ('historical_observation','simulated_future_truth')"),
    sa.CheckConstraint('rain_mm_per_hour >= 0'),
    sa.CheckConstraint('visibility_m >= 0'),
    sa.CheckConstraint('wind_mps >= 0'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_id', 'timestamp')
    )
    op.create_index('ix_weather_lookup', 'weather', ['port_id', 'timestamp'], unique=False)
    op.create_table('berths',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('terminal_id', sa.String(length=160), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('depth_m', sa.Float(), nullable=False),
    sa.Column('under_keel_clearance_m', sa.Float(), nullable=False),
    sa.Column('equipment', sa.String(length=160), nullable=False),
    sa.Column('max_cranes', sa.Integer(), nullable=False),
    sa.CheckConstraint("equipment IN ('panamax_sts','super_post_panamax_sts')"),
    sa.CheckConstraint('depth_m >= 0'),
    sa.CheckConstraint('length_m >= 0'),
    sa.CheckConstraint('max_cranes >= 0'),
    sa.CheckConstraint('under_keel_clearance_m >= 0'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supervisor_plans',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', UTCInstant(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimisation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('vessel_calls',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('vessel_id', sa.String(length=160), nullable=False),
    sa.Column('terminal_id', sa.String(length=160), nullable=False),
    sa.Column('period', sa.String(length=160), nullable=False),
    sa.Column('scheduled_eta', UTCInstant(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('cargo_type', sa.String(length=160), nullable=False),
    sa.Column('onboard_teu', sa.Integer(), nullable=False),
    sa.Column('unload_moves', sa.Integer(), nullable=False),
    sa.Column('load_moves', sa.Integer(), nullable=False),
    sa.Column('teu_per_move', sa.Float(), nullable=False),
    sa.CheckConstraint("cargo_type IN ('general','hazardous','reefer')"),
    sa.CheckConstraint("period IN ('historical','upcoming')"),
    sa.CheckConstraint('load_moves >= 0'),
    sa.CheckConstraint('onboard_teu >= 0'),
    sa.CheckConstraint('priority >= 0'),
    sa.CheckConstraint('priority BETWEEN 1 AND 5 AND teu_per_move BETWEEN 1 AND 2'),
    sa.CheckConstraint('teu_per_move >= 0'),
    sa.CheckConstraint('unload_moves >= 0'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vessel_calls_lookup', 'vessel_calls', ['terminal_id', 'scheduled_eta'], unique=False)
    op.create_table('yard_snapshots',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('terminal_id', sa.String(length=160), nullable=False),
    sa.Column('timestamp', UTCInstant(), nullable=False),
    sa.Column('opening_teu', sa.Float(), nullable=False),
    sa.Column('gate_outbound_teu', sa.Float(), nullable=False),
    sa.Column('inbound_teu', sa.Float(), nullable=False),
    sa.Column('outbound_teu', sa.Float(), nullable=False),
    sa.Column('closing_teu', sa.Float(), nullable=False),
    sa.Column('queued_vessels', sa.Integer(), nullable=False),
    sa.CheckConstraint('closing_teu >= 0'),
    sa.CheckConstraint('gate_outbound_teu >= 0'),
    sa.CheckConstraint('inbound_teu >= 0'),
    sa.CheckConstraint('opening_teu >= 0'),
    sa.CheckConstraint('outbound_teu >= 0'),
    sa.CheckConstraint('queued_vessels >= 0'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_id', 'timestamp')
    )
    op.create_index('ix_yard_snapshots_lookup', 'yard_snapshots', ['terminal_id', 'timestamp'], unique=False)
    op.create_table('approval_events',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('plan_id', sa.String(length=160), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', UTCInstant(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['supervisor_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('berth_assignments',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('call_id', sa.String(length=160), nullable=False),
    sa.Column('berth_id', sa.String(length=160), nullable=False),
    sa.Column('start', UTCInstant(), nullable=False),
    sa.Column('end', UTCInstant(), nullable=False),
    sa.Column('waiting_minutes', sa.Integer(), nullable=False),
    sa.Column('planned_moves', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.CheckConstraint('"end" > "start" AND waiting_minutes >= 0 AND planned_moves > 0'),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['vessel_calls.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['optimisation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'call_id')
    )
    op.create_index(op.f('ix_berth_assignments_run_id'), 'berth_assignments', ['run_id'], unique=False)
    op.create_table('berth_cargo_compatibility',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('berth_id', sa.String(length=160), nullable=False),
    sa.Column('cargo_type', sa.String(length=160), nullable=False),
    sa.CheckConstraint("cargo_type IN ('general','hazardous','reefer')"),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('berth_id', 'cargo_type')
    )
    op.create_table('call_outcomes',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('call_id', sa.String(length=160), nullable=False),
    sa.Column('berth_id', sa.String(length=160), nullable=False),
    sa.Column('period', sa.String(length=160), nullable=False),
    sa.Column('actual_arrival', UTCInstant(), nullable=False),
    sa.Column('berth_start', UTCInstant(), nullable=False),
    sa.Column('service_completion', UTCInstant(), nullable=False),
    sa.Column('departure', UTCInstant(), nullable=False),
    sa.Column('waiting_hours', sa.Float(), nullable=False),
    sa.Column('assigned_cranes', sa.Integer(), nullable=False),
    sa.Column('crane_hours', sa.Float(), nullable=False),
    sa.CheckConstraint("period IN ('historical','simulated_future_truth')"),
    sa.CheckConstraint('assigned_cranes >= 0'),
    sa.CheckConstraint('berth_start >= actual_arrival AND service_completion > berth_start AND departure >= service_completion'),
    sa.CheckConstraint('crane_hours >= 0'),
    sa.CheckConstraint('waiting_hours >= 0'),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['call_id'], ['vessel_calls.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('congestion_forecasts',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('port_id', sa.String(length=160), nullable=False),
    sa.Column('berth_id', sa.String(length=160), nullable=False),
    sa.Column('timestamp', UTCInstant(), nullable=False),
    sa.Column('demand_moves', sa.Float(), nullable=False),
    sa.Column('capacity_moves', sa.Float(), nullable=False),
    sa.Column('pressure_ratio', sa.Float(), nullable=False),
    sa.Column('alert', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.CheckConstraint('demand_moves >= 0 AND capacity_moves >= 0 AND pressure_ratio >= 0'),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'berth_id', 'timestamp')
    )
    op.create_index(op.f('ix_congestion_forecasts_port_id'), 'congestion_forecasts', ['port_id'], unique=False)
    op.create_index(op.f('ix_congestion_forecasts_run_id'), 'congestion_forecasts', ['run_id'], unique=False)
    op.create_index(op.f('ix_congestion_forecasts_timestamp'), 'congestion_forecasts', ['timestamp'], unique=False)
    op.create_table('cranes',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('berth_id', sa.String(length=160), nullable=False),
    sa.Column('equipment', sa.String(length=160), nullable=False),
    sa.Column('productivity_moves_per_hour', sa.Float(), nullable=False),
    sa.CheckConstraint("equipment IN ('panamax_sts','super_post_panamax_sts')"),
    sa.CheckConstraint('productivity_moves_per_hour >= 0'),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handling_log',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('call_id', sa.String(length=160), nullable=False),
    sa.Column('timestamp', UTCInstant(), nullable=False),
    sa.Column('active_cranes', sa.Integer(), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('weather_factor', sa.Float(), nullable=False),
    sa.Column('yard_factor', sa.Float(), nullable=False),
    sa.Column('coordination_factor', sa.Float(), nullable=False),
    sa.Column('productive_fraction', sa.Float(), nullable=False),
    sa.Column('handled_moves', sa.Float(), nullable=False),
    sa.Column('inbound_teu', sa.Float(), nullable=False),
    sa.Column('outbound_teu', sa.Float(), nullable=False),
    sa.CheckConstraint('active_cranes >= 0'),
    sa.CheckConstraint('base_rate >= 0'),
    sa.CheckConstraint('coordination_factor >= 0'),
    sa.CheckConstraint('handled_moves >= 0'),
    sa.CheckConstraint('inbound_teu >= 0'),
    sa.CheckConstraint('outbound_teu >= 0'),
    sa.CheckConstraint('productive_fraction >= 0'),
    sa.CheckConstraint('weather_factor >= 0'),
    sa.CheckConstraint('yard_factor >= 0'),
    sa.ForeignKeyConstraint(['call_id'], ['vessel_calls.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'timestamp')
    )
    op.create_table('routing_recommendations',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('call_id', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('alternate_port_id', sa.String(length=160), nullable=True),
    sa.Column('adjusted_eta', UTCInstant(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['alternate_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['vessel_calls.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['optimisation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_recommendations_run_id'), 'routing_recommendations', ['run_id'], unique=False)
    op.create_table('supervisor_shift_plans',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('plan_id', sa.String(length=160), nullable=False),
    sa.Column('shift_index', sa.Integer(), nullable=False),
    sa.Column('start', UTCInstant(), nullable=False),
    sa.Column('end', UTCInstant(), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.CheckConstraint('shift_index BETWEEN 0 AND 8 AND "end" > "start"'),
    sa.ForeignKeyConstraint(['plan_id'], ['supervisor_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'shift_index')
    )
    op.create_index(op.f('ix_supervisor_shift_plans_plan_id'), 'supervisor_shift_plans', ['plan_id'], unique=False)
    op.create_table('crane_assignments',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('call_id', sa.String(length=160), nullable=False),
    sa.Column('crane_id', sa.String(length=160), nullable=False),
    sa.Column('start', UTCInstant(), nullable=False),
    sa.Column('end', UTCInstant(), nullable=False),
    sa.CheckConstraint('"end" > "start"'),
    sa.ForeignKeyConstraint(['call_id'], ['vessel_calls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['crane_id'], ['cranes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'crane_id')
    )
    op.create_table('disruptions',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('port_id', sa.String(length=160), nullable=False),
    sa.Column('terminal_id', sa.String(length=160), nullable=True),
    sa.Column('crane_id', sa.String(length=160), nullable=True),
    sa.Column('call_id', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.String(length=160), nullable=False),
    sa.Column('start', UTCInstant(), nullable=False),
    sa.Column('end', UTCInstant(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.CheckConstraint("kind IN ('arrival_surge','crane_breakdown','late_arrival','storm','yard_congestion')"),
    sa.CheckConstraint('"end" > "start"'),
    sa.CheckConstraint('value >= 0'),
    sa.ForeignKeyConstraint(['call_id'], ['vessel_calls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['crane_id'], ['cranes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_crane_assignments',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('assignment_id', sa.String(length=160), nullable=False),
    sa.Column('crane_id', sa.String(length=160), nullable=False),
    sa.Column('start', UTCInstant(), nullable=False),
    sa.Column('end', UTCInstant(), nullable=False),
    sa.CheckConstraint('"end" > "start"'),
    sa.ForeignKeyConstraint(['assignment_id'], ['berth_assignments.id'], ),
    sa.ForeignKeyConstraint(['crane_id'], ['cranes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'crane_id')
    )
    op.create_index(op.f('ix_plan_crane_assignments_assignment_id'), 'plan_crane_assignments', ['assignment_id'], unique=False)
    op.create_table('crane_availability',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('crane_id', sa.String(length=160), nullable=False),
    sa.Column('start', UTCInstant(), nullable=False),
    sa.Column('end', UTCInstant(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('disruption_id', sa.String(length=160), nullable=True),
    sa.CheckConstraint("reason IN ('breakdown','maintenance')"),
    sa.CheckConstraint('"end" > "start"'),
    sa.ForeignKeyConstraint(['crane_id'], ['cranes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crane_availability')
    op.drop_index(op.f('ix_plan_crane_assignments_assignment_id'), table_name='plan_crane_assignments')
    op.drop_table('plan_crane_assignments')
    op.drop_table('disruptions')
    op.drop_table('crane_assignments')
    op.drop_index(op.f('ix_supervisor_shift_plans_plan_id'), table_name='supervisor_shift_plans')
    op.drop_table('supervisor_shift_plans')
    op.drop_index(op.f('ix_routing_recommendations_run_id'), table_name='routing_recommendations')
    op.drop_table('routing_recommendations')
    op.drop_table('handling_log')
    op.drop_table('cranes')
    op.drop_index(op.f('ix_congestion_forecasts_timestamp'), table_name='congestion_forecasts')
    op.drop_index(op.f('ix_congestion_forecasts_run_id'), table_name='congestion_forecasts')
    op.drop_index(op.f('ix_congestion_forecasts_port_id'), table_name='congestion_forecasts')
    op.drop_table('congestion_forecasts')
    op.drop_table('call_outcomes')
    op.drop_table('berth_cargo_compatibility')
    op.drop_index(op.f('ix_berth_assignments_run_id'), table_name='berth_assignments')
    op.drop_table('berth_assignments')
    op.drop_table('approval_events')
    op.drop_index('ix_yard_snapshots_lookup', table_name='yard_snapshots')
    op.drop_table('yard_snapshots')
    op.drop_index('ix_vessel_calls_lookup', table_name='vessel_calls')
    op.drop_table('vessel_calls')
    op.drop_table('supervisor_plans')
    op.drop_table('berths')
    op.drop_index('ix_weather_lookup', table_name='weather')
    op.drop_table('weather')
    op.drop_index('ix_tides_lookup', table_name='tides')
    op.drop_table('tides')
    op.drop_table('terminals')
    op.drop_table('optimisation_runs')
    op.drop_table('vessels')
    op.drop_table('seed_provenance')
    op.drop_table('scenarios')
    op.drop_table('ports')
    op.drop_table('forecast_runs')
    op.drop_table('demo_dataset')
    # ### end Alembic commands ###
