"""represent undefined capacity ratios as null

Revision ID: 0004
Revises: 0003
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('congestion_forecasts', schema=None) as batch_op:
        batch_op.alter_column('pressure_ratio',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('congestion_forecasts', schema=None) as batch_op:
        batch_op.alter_column('pressure_ratio',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
