"""executable crane shifts and plan reassignment

Revision ID: 0008
Revises: 0007
"""
from alembic import op
import sqlalchemy as sa
from app.synthetic.storage import UTCInstant

revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('berth_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_time', UTCInstant(), nullable=True))
        batch_op.add_column(sa.Column('execution_profile', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('superseded_at', UTCInstant(), nullable=True))

    old = next(c for c in sa.inspect(op.get_bind()).get_unique_constraints('plan_crane_assignments')
               if c['column_names'] == ['assignment_id', 'crane_id'])
    convention = {'uq': 'uq_%(table_name)s_%(column_0_name)s'}
    with op.batch_alter_table('plan_crane_assignments', naming_convention=convention) as batch_op:
        batch_op.drop_constraint(old['name'] or 'uq_plan_crane_assignments_assignment_id', type_='unique')
        batch_op.create_unique_constraint('uq_plan_crane_assignments_segment', ['assignment_id', 'crane_id', 'start'])

    # ### end Alembic commands ###


def downgrade():
    duplicate = op.get_bind().execute(sa.text('SELECT assignment_id FROM plan_crane_assignments GROUP BY assignment_id, crane_id HAVING COUNT(*) > 1')).first()
    if duplicate:
        raise RuntimeError('Downgrade would lose executable crane segments; export/archive optimisation runs before downgrading')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_crane_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_plan_crane_assignments_segment', type_='unique')
        batch_op.create_unique_constraint('uq_plan_crane_assignments_assignment_id', ['assignment_id', 'crane_id'])

    with op.batch_alter_table('berth_assignments', schema=None) as batch_op:
        batch_op.drop_column('superseded_at')
        batch_op.drop_column('execution_profile')
        batch_op.drop_column('completion_time')

    # ### end Alembic commands ###
