"""preserve observed in progress work

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa
from app.synthetic.storage import UTCInstant

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carry_in_operations',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('call_id', sa.String(length=160), nullable=False),
    sa.Column('berth_id', sa.String(length=160), nullable=False),
    sa.Column('known_at', UTCInstant(), nullable=False),
    sa.Column('started_at', UTCInstant(), nullable=False),
    sa.Column('remaining_moves', sa.Float(), nullable=False),
    sa.Column('crane_ids', sa.JSON(), nullable=False),
    sa.CheckConstraint('remaining_moves >= 0 AND known_at >= started_at'),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['vessel_calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carry_in_operations')
    # ### end Alembic commands ###
