"""atomic planning revision gate

Revision ID: 0003
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.CheckConstraint('revision >= 1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(sa.text('INSERT INTO planning_state (id, revision) VALUES (1, 1)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planning_state')
    # ### end Alembic commands ###
