"""persist predictive congestion and vessel waiting estimates

Revision ID: 0005
Revises: 0004
"""
from alembic import op
import sqlalchemy as sa
from app.synthetic.storage import UTCInstant

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictive_congestion',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('port_id', sa.String(length=160), nullable=False),
    sa.Column('terminal_id', sa.String(length=160), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=160), nullable=False),
    sa.Column('timestamp', UTCInstant(), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('lower', sa.Float(), nullable=False),
    sa.Column('upper', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('level_probabilities', sa.JSON(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prediction_timestamp', UTCInstant(), nullable=False),
    sa.Column('uncertainty_method', sa.String(length=64), nullable=False),
    sa.Column('nominal_coverage', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=64), nullable=False),
    sa.CheckConstraint("(scope = 'port' AND terminal_id IS NULL AND scope_id = port_id) OR (scope = 'terminal' AND terminal_id IS NOT NULL AND scope_id = terminal_id)"),
    sa.CheckConstraint("scope IN ('port', 'terminal') AND level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')"),
    sa.CheckConstraint('prediction >= 0 AND prediction <= 1 AND lower >= 0 AND upper <= 1 AND lower <= prediction AND upper >= prediction'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'scope', 'scope_id', 'timestamp')
    )
    with op.batch_alter_table('predictive_congestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictive_congestion_port_id'), ['port_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictive_congestion_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictive_congestion_terminal_id'), ['terminal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictive_congestion_timestamp'), ['timestamp'], unique=False)

    op.create_table('vessel_waiting_predictions',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('call_id', sa.String(length=160), nullable=False),
    sa.Column('port_id', sa.String(length=160), nullable=False),
    sa.Column('terminal_id', sa.String(length=160), nullable=False),
    sa.Column('scheduled_eta', UTCInstant(), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('lower', sa.Float(), nullable=False),
    sa.Column('upper', sa.Float(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prediction_timestamp', UTCInstant(), nullable=False),
    sa.Column('uncertainty_method', sa.String(length=64), nullable=False),
    sa.Column('nominal_coverage', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=64), nullable=False),
    sa.CheckConstraint('prediction >= 0 AND lower >= 0 AND lower <= prediction AND upper >= prediction'),
    sa.ForeignKeyConstraint(['call_id'], ['vessel_calls.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'call_id')
    )
    with op.batch_alter_table('vessel_waiting_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vessel_waiting_predictions_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vessel_waiting_predictions_run_id'), ['run_id'], unique=False)

    with op.batch_alter_table('forecast_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_version', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast_runs', schema=None) as batch_op:
        batch_op.drop_column('model_version')

    with op.batch_alter_table('vessel_waiting_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vessel_waiting_predictions_run_id'))
        batch_op.drop_index(batch_op.f('ix_vessel_waiting_predictions_call_id'))

    op.drop_table('vessel_waiting_predictions')
    with op.batch_alter_table('predictive_congestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictive_congestion_timestamp'))
        batch_op.drop_index(batch_op.f('ix_predictive_congestion_terminal_id'))
        batch_op.drop_index(batch_op.f('ix_predictive_congestion_run_id'))
        batch_op.drop_index(batch_op.f('ix_predictive_congestion_port_id'))

    op.drop_table('predictive_congestion')
    # ### end Alembic commands ###
