"""observe arrival and berth events without future completions

Revision ID: 0006
Revises: 0005
"""
from alembic import op
import sqlalchemy as sa
from app.synthetic.storage import UTCInstant

revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel_call_observations',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('call_id', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('timestamp', UTCInstant(), nullable=False),
    sa.Column('berth_id', sa.String(length=160), nullable=True),
    sa.CheckConstraint("kind = 'arrival' OR berth_id IS NOT NULL"),
    sa.CheckConstraint("kind IN ('arrival', 'berth_start', 'departure')"),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['vessel_calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'kind')
    )
    with op.batch_alter_table('vessel_call_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vessel_call_observations_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vessel_call_observations_timestamp'), ['timestamp'], unique=False)

    # Completed app outcomes are observed facts; preserve them on upgrades.
    for kind, field in [('arrival', 'actual_arrival'), ('berth_start', 'berth_start'), ('departure', 'departure')]:
        berth = 'NULL' if kind == 'arrival' else 'berth_id'
        op.execute(sa.text(f"INSERT INTO vessel_call_observations (id, call_id, kind, timestamp, berth_id) "
            f"SELECT call_id || ':' || '{kind}', call_id, '{kind}', {field}, {berth} FROM call_outcomes"))
    op.execute(sa.text("INSERT INTO vessel_call_observations (id, call_id, kind, timestamp, berth_id) "
        "SELECT call_id || ':' || 'berth_start', call_id, 'berth_start', started_at, berth_id FROM carry_in_operations c "
        "WHERE NOT EXISTS (SELECT 1 FROM vessel_call_observations o WHERE o.call_id = c.call_id AND o.kind = 'berth_start')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vessel_call_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vessel_call_observations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_vessel_call_observations_call_id'))

    op.drop_table('vessel_call_observations')
    # ### end Alembic commands ###
