"""hourly early warning and alert lifecycle

Revision ID: 0007
Revises: 0006
"""
from alembic import op
import sqlalchemy as sa
from app.synthetic.storage import UTCInstant

revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_watermarks',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('as_of', UTCInstant(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.CheckConstraint('revision >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('early_warning_runs',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('projection_method', sa.String(length=64), nullable=False),
    sa.Column('summaries', sa.JSON(), nullable=False),
    sa.Column('alert_counts', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('congestion_alerts',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('active_key', sa.String(length=240), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=160), nullable=False),
    sa.Column('port_id', sa.String(length=160), nullable=False),
    sa.Column('terminal_id', sa.String(length=160), nullable=True),
    sa.Column('berth_id', sa.String(length=160), nullable=True),
    sa.Column('rule_code', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('opened_at', UTCInstant(), nullable=False),
    sa.Column('updated_at', UTCInstant(), nullable=False),
    sa.Column('first_run_id', sa.String(length=160), nullable=False),
    sa.Column('last_run_id', sa.String(length=160), nullable=False),
    sa.Column('expected_start', UTCInstant(), nullable=False),
    sa.Column('expected_end', UTCInstant(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=120), nullable=True),
    sa.Column('acknowledged_at', UTCInstant(), nullable=True),
    sa.Column('resolved_at', UTCInstant(), nullable=True),
    sa.CheckConstraint("(state = 'RESOLVED' AND active_key IS NULL AND resolved_at IS NOT NULL) OR (state != 'RESOLVED' AND active_key IS NOT NULL AND resolved_at IS NULL)"),
    sa.CheckConstraint("scope IN ('port', 'terminal', 'berth')"),
    sa.CheckConstraint("state IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')"),
    sa.CheckConstraint('revision >= 1 AND duration_hours BETWEEN 1 AND 72 AND expected_end > expected_start'),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['first_run_id'], ['early_warning_runs.id'], ),
    sa.ForeignKeyConstraint(['last_run_id'], ['early_warning_runs.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_key')
    )
    op.create_table('operational_forecasts',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=160), nullable=False),
    sa.Column('port_id', sa.String(length=160), nullable=False),
    sa.Column('terminal_id', sa.String(length=160), nullable=True),
    sa.Column('berth_id', sa.String(length=160), nullable=True),
    sa.Column('timestamp', UTCInstant(), nullable=False),
    sa.Column('berth_utilisation', sa.Float(), nullable=False),
    sa.Column('queue_length', sa.Float(), nullable=False),
    sa.Column('average_wait_hours', sa.Float(), nullable=False),
    sa.Column('yard_occupancy', sa.Float(), nullable=False),
    sa.Column('crane_utilisation', sa.Float(), nullable=False),
    sa.Column('congestion_probability', sa.Float(), nullable=False),
    sa.Column('probability_lower', sa.Float(), nullable=False),
    sa.Column('probability_upper', sa.Float(), nullable=False),
    sa.Column('probability_basis', sa.String(length=32), nullable=False),
    sa.Column('congestion_severity', sa.String(length=16), nullable=False),
    sa.Column('confidence_level', sa.String(length=16), nullable=False),
    sa.Column('confidence_reasons', sa.JSON(), nullable=False),
    sa.Column('main_causes', sa.JSON(), nullable=False),
    sa.Column('arrival_workload_ratio', sa.Float(), nullable=False),
    sa.Column('arrival_workload_increase_moves', sa.Float(), nullable=False),
    sa.Column('is_hotspot', sa.Integer(), nullable=False),
    sa.Column('first_expected_hotspot_time', UTCInstant(), nullable=True),
    sa.Column('expected_hotspot_duration_hours', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prediction_timestamp', UTCInstant(), nullable=False),
    sa.CheckConstraint("(scope = 'port' AND scope_id = port_id AND terminal_id IS NULL AND berth_id IS NULL) OR (scope = 'terminal' AND scope_id = terminal_id AND berth_id IS NULL) OR (scope = 'berth' AND scope_id = berth_id AND terminal_id IS NOT NULL)"),
    sa.CheckConstraint("congestion_severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') AND confidence_level IN ('LOW', 'MEDIUM', 'HIGH')"),
    sa.CheckConstraint("scope IN ('port', 'terminal', 'berth')"),
    sa.CheckConstraint('berth_utilisation BETWEEN 0 AND 1 AND yard_occupancy BETWEEN 0 AND 1 AND crane_utilisation BETWEEN 0 AND 1'),
    sa.CheckConstraint('expected_hotspot_duration_hours BETWEEN 0 AND 72 AND is_hotspot IN (0, 1)'),
    sa.CheckConstraint('probability_lower >= 0 AND probability_upper <= 1 AND probability_lower <= congestion_probability AND congestion_probability <= probability_upper'),
    sa.CheckConstraint('queue_length >= 0 AND average_wait_hours >= 0 AND arrival_workload_ratio >= 0 AND arrival_workload_increase_moves >= 0'),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['early_warning_runs.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'scope', 'scope_id', 'timestamp')
    )
    with op.batch_alter_table('operational_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_forecasts_run_id'), ['run_id'], unique=False)

    op.create_table('alert_events',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('alert_id', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('occurred_at', UTCInstant(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['congestion_alerts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['early_warning_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_alert_id'), ['alert_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_alert_id'))

    op.drop_table('alert_events')
    with op.batch_alter_table('operational_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_forecasts_run_id'))

    op.drop_table('operational_forecasts')
    op.drop_table('congestion_alerts')
    op.drop_table('early_warning_runs')
    op.drop_table('alert_watermarks')
    # ### end Alembic commands ###
