// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {cleanup,configure,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import { App } from './App';
import {fixture} from './testing/fixture';

configure({asyncUtilTimeout:10000});
beforeEach(()=>{history.replaceState(null,'','/');vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}})});
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.restoreAllMocks()});
function mockApi(data=fixture()) {const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);if(url.endsWith('/review')){data.run.plan!.status='REVIEWED';data.run.plan!.revision=2;return new Response(JSON.stringify(data.run.plan))}if(url.endsWith('/approve')){data.run.plan!.status='APPROVED';data.run.plan!.revision=3;return new Response(JSON.stringify(data.run.plan))}return new Response(JSON.stringify(data))});vi.stubGlobal('fetch',fetcher);return fetcher}

describe('operations command centre',()=>{
  it('retains the requested run when authentication follows the first blocked load',async()=>{
    history.replaceState(null,'','/?run=run-requested');let authenticated=false;
    Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(this:HTMLDialogElement){this.setAttribute('open','')}});
    Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(this:HTMLDialogElement){this.removeAttribute('open')}});
    const fetcher=vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);
      if(url.endsWith('/auth/status'))return new Response(JSON.stringify({required:true,authenticated}));
      if(url.endsWith('/auth/session')){authenticated=true;return new Response('{}')}
      return authenticated?new Response(JSON.stringify(fixture())):new Response(JSON.stringify({error:{message:'Operator access required'}}),{status:401});
    });vi.stubGlobal('fetch',fetcher);render(<App/>);await screen.findByRole('alert');
    await userEvent.click(screen.getByRole('button',{name:'Operator access'}));await userEvent.type(await screen.findByLabelText('Operator access key'),'quay-local-demo-only-operator-key-2026');
    await userEvent.click(screen.getByRole('button',{name:'Unlock operations'}));await screen.findByText('Scheduled test vessel');
    const loads=fetcher.mock.calls.filter(([url])=>String(url).includes('/dashboard'));expect(loads).toHaveLength(2);expect(String(loads[1][0])).toContain('/dashboard?run_id=run-requested');
  });
  it('shows loading and then sourced vessel predictions',async()=>{mockApi();render(<App/>);expect(screen.getByText('Preparing your command centre')).toBeInTheDocument();await screen.findByText('Scheduled test vessel');expect(screen.getAllByText('15 h').length).toBeGreaterThan(0);expect(screen.getByText('No trained outlook available for this run.')).toBeInTheDocument()});
  it('uses the supplied project logo for the dashboard brand',async()=>{mockApi();render(<App/>);const logo=await screen.findByAltText('QUAY project logo');expect(logo).toHaveAttribute('src','/quay-logo.png')});
  it('shows API errors and supports retry',async()=>{let failed=false;const fetcher=vi.fn(async(url:RequestInfo|URL)=>{if(String(url).endsWith('/auth/status'))return new Response(JSON.stringify({required:false,authenticated:true}));if(!failed){failed=true;return new Response(JSON.stringify({error:{message:'Seed dataset missing'}}),{status:404})}return new Response(JSON.stringify(fixture()))});vi.stubGlobal('fetch',fetcher);render(<App/>);expect(await screen.findByRole('alert')).toHaveTextContent('Seed dataset missing');await userEvent.click(screen.getByRole('button',{name:'Retry loading'}));expect(await screen.findByText('Scheduled test vessel')).toBeInTheDocument()});
  it('filters risks using selected API port data',async()=>{mockApi();render(<App/>);await screen.findByText('Scheduled test vessel');await userEvent.selectOptions(screen.getByLabelText('Port scope'),'P02');expect(screen.queryByText('Scheduled test vessel')).not.toBeInTheDocument();expect(screen.getByText('No waiting predictions available for this run and scope.')).toBeInTheDocument()});
  it('uses revision-checked review before approval',async()=>{const fetcher=mockApi();render(<App/>);await screen.findByText('Scheduled test vessel');await userEvent.click(screen.getByRole('button',{name:'Supervisor shift plan'}));const approval=await screen.findByRole('button',{name:'Approve plan'});expect(approval).toBeDisabled();await userEvent.clear(screen.getByLabelText('Supervisor name'));await userEvent.type(screen.getByLabelText('Supervisor name'),'Shift lead');await userEvent.click(screen.getByRole('button',{name:'Mark reviewed'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Approve plan'})).toBeEnabled());await userEvent.click(screen.getByRole('button',{name:'Approve plan'}));await screen.findByText('APPROVED');const posts=fetcher.mock.calls.filter(([,options])=>options?.method==='POST');expect(JSON.parse(posts[0][1]!.body as string)).toEqual({actor:'Shift lead',expected_revision:1});expect(JSON.parse(posts[1][1]!.body as string)).toEqual({actor:'Shift lead',expected_revision:2})},20000);
  it('prevents operational approval of hypothetical scenarios',async()=>{const data=fixture();data.run.scenario_id='scenario-a';mockApi(data);render(<App/>);await screen.findByText('Scheduled test vessel');await userEvent.click(screen.getByRole('button',{name:'Supervisor shift plan'}));expect(await screen.findByRole('button',{name:'Mark reviewed'})).toBeDisabled();expect(screen.getByRole('button',{name:'Approve plan'})).toBeDisabled();expect(screen.getByRole('button',{name:/Create operational draft/})).toBeEnabled()});
  it('navigates all nine shifts and exposes handover notes',async()=>{mockApi();render(<App/>);await screen.findByText('Scheduled test vessel');await userEvent.click(screen.getByRole('button',{name:'Supervisor shift plan'}));const tabs=await screen.findAllByRole('tab');expect(tabs).toHaveLength(9);await userEvent.click(tabs[8]);expect(tabs[8]).toHaveAttribute('aria-selected','true');expect(screen.getByText('Confirm crane ownership')).toBeInTheDocument()});
  it('prioritises supervisor decisions and keeps the complete evidence collapsed',async()=>{mockApi();render(<App/>);await screen.findByText('Scheduled test vessel');await userEvent.click(screen.getByRole('button',{name:'Supervisor shift plan'}));expect(await screen.findByText('Top decisions for this shift')).toBeInTheDocument();expect(screen.getAllByText('Reconcile measured progress')).toHaveLength(2);expect(screen.getByText('Decision deadline')).toBeInTheDocument();expect(screen.getByText(/All 1 recorded actions and evidence/)).toBeInTheDocument()});
  it('loads a persisted run when the dataset control changes',async()=>{const fetcher=mockApi();render(<App/>);await screen.findByText('Scheduled test vessel');await userEvent.selectOptions(screen.getByLabelText('Persisted plan or scenario'),'run-b');await waitFor(()=>expect(fetcher.mock.calls.some(([url])=>String(url).endsWith('/dashboard?run_id=run-b'))).toBe(true))});
  it('keeps the full operational scope when drafting from a filtered port view',async()=>{const fetcher=mockApi();render(<App/>);await screen.findByText('Scheduled test vessel');await userEvent.selectOptions(screen.getByLabelText('Port scope'),'P01');await userEvent.click(screen.getByRole('button',{name:'Supervisor shift plan'}));await userEvent.click(screen.getByRole('button',{name:/Create operational draft/}));await waitFor(()=>expect(fetcher.mock.calls.some(([url])=>String(url).endsWith('/optimisation/run'))).toBe(true));const call=fetcher.mock.calls.find(([url])=>String(url).endsWith('/optimisation/run'));expect(JSON.parse(call![1]!.body as string).port_ids).toEqual(['P01','P02'])});
  it('uses the backend risk threshold rather than a frontend operational constant',async()=>{const data=fixture();data.risk_wait_threshold_hours=20;mockApi(data);render(<App/>);await screen.findByText('Predicted wait exceeds 20 hours');expect(screen.queryByText('Scheduled test vessel')).not.toBeInTheDocument()});
});
